### ISSUE TITLE
Screenshots update required for GNOME appdata file

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#101]
Screenshots in dev/gnome/engauge-screenshots still feature Engauge 6. Would be good to have updated look. Just like @sagitter has done in Fedora http://pkgs.fedoraproject.org/cgit/rpms/engauge-digitizer.git/tree/engauge-digitizer.appdata.xml

**Comment by markummitchell** [comment]
I've checked in newer images. Are those what  you were expecting?

**Comment by crayxt** [comment]
Yes, much better, thanks
