### ISSUE TITLE
Export is only in comma separated format with comma delimited numbers

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#102]
Export is not working for a sample file. The Export As delimiter is being ignored and commas are used instead, while commas are also being used for the thousandths' place. Downstream tools do not know which commas separate numbers and which commas designate the thousandth's place.

**Comment by crayxt** [comment]
Need to use quotes?

**Comment by markummitchell** [comment]
I received a dig file that insists on using commas as delimiters despite the user's choice of other delimiters. This is impolite behavior. Should be easy to fix when I get home. As you mentioned, a separate issue is that maybe quotes should be inserted around fields with commas when commas are actually selected as delimiters.

**Comment by markummitchell** [comment]
The group delimiter is removed from exported numbers (1,000,000 becomes 1000000) to prevent ambiguity with commas (between numbers and within numbers).
