### ISSUE TITLE
[OSX] Small Checklist Dialog; Cannot Be Resized

### ISSUE THREAD

**Issue by jkulesza** [markummitchell/engauge-digitizer#103]
The checklist displayed after an image is imported is quite small.  While it can be scrolled, it cannot be resized.

<img width="374" alt="screen shot 2016-03-22 at 7 27 36 am" src="https://cloud.githubusercontent.com/assets/9939059/13950140/a1be8f2a-efff-11e5-9b9d-937f1118d1a0.png">

This is on OSX 10.11.3.

**Comment by markummitchell** [comment]
The checklist can be dragged out of its docking position

Yesterday I watched a new user not notice the small checklist dialog, causing much pain. There seemed to be two solutions to make it more visible, but now after some thought there are two more options:
1) Start the checklist floating the way it was before and hope users see it
2) Start the checklist in the docked position (and hope they notice that it can be resized and/or undocked)
3) Start the checklist floating, but make sure it is bigger than some threshold so it is noticeable
4) Start the checklist in the docked position and insert a comment explaining that it can be resized and/or undocked

Also, the docked checklist should be resizable. Something is broken if it is not.

Suggestions?

**Comment by jkulesza** [comment]
The checklist guide doesn't appear to be within a dock (from what I can tell).  I can freely drag it around the entire screen and it exhibits not behavior suggesting it can/will leave/enter a dock-type container.  

Despite dragging it to different positions, I cannot resize it.

**Comment by markummitchell** [comment]
Sounds like https://bugreports.qt.io/browse/QTBUG-46882. There is a patch
there which may not be useful. I'll look into the patch and/or maybe
hacking the Engauge code, when I get back to an OSX system and can
duplicate the problem.

**Comment by markummitchell** [comment]
The checklist wizard is docked when it first appears, which allows resizing by sliding the splitter. When the size is good, it can be undocked. Unfortunately, due to https://bugreports.qt.io/browse/QTBUG-46882 the checklist wizard cannot be resized when undocked in OSX. In Windows and Linux the checklist wizard can be resized when undocked.
