### ISSUE TITLE
make make install work

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#115]
See https://doc.qt.io/qt-5/qmake-advanced-usage.html#installing-files

I'd like to install files on unix with ```make install```, instead of copying them manually.

**Comment by markummitchell** [comment]
That's a good enhancement.

**Comment by crayxt** [comment]
I am quite far from even starting this. @markummitchell I think we can close this for now?

**Comment by markummitchell** [comment]
Sure, perhaps even permanently. OS differences with /opt, /usr/share and similar might have made it a real challenge. And I'm busy with OSX and grid display.
