### ISSUE TITLE
windows: engauge_release tracking in windows

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#116]
Currently one must specify ```ENGAUGE_RELEASE=1``` to make release/nodebug build of engauge.
On Windows, ```ENGAUGE_RELEASE``` must additionally track the state of ```Configuration``` env var, which could be either ```Release``` or ```Debug```.

**Comment by markummitchell** [comment]
Perhaps 'make release' should be used instead of 'ENGAUGE_RELEASE=1; make'

**Comment by markummitchell** [comment]
I think this is cleaned up now. Comments:
* The scripts now build 'release' versions by default
* The scripts document how 'CONFIG+=debug' is used to build a debug version
* JPEG2000 compilation and linking is much improved (Test case is a *.jp2 file in samples directory)
* ENGAUGE_RELEASE environment variable is no longer used (too clumsy)
