### ISSUE TITLE
When two data points have the exact same x-value, only one of them is exported

### ISSUE THREAD

**Issue by wilthan** [markummitchell/engauge-digitizer#120]
When the axis definition points are exactly aligned (square) and two data points have the same x-value, then only one of the data points is exported.

The attached example file (Engauge 7.2) shows such a scenario. 
[Glitch demo.zip](https://github.com/markummitchell/engauge-digitizer/files/226188/Glitch.demo.zip)
In the lower left corner there are two data points, only one is displayed. The preview in Settings/export format also only show one point.
Now mark the data point and move it one pixel pixel out of alignment, left or right, with the cursor - the second point appears. Now, check the export again. 

You should see both curve points represented in the export.
To repeat the faulty results, return to the plot and move the point back to where it was and now the export will only show one curve point.

It doesn't happen too often but we had quite a few cases where we missed points because of that. 

Thx for addressing this issue!

**Comment by markummitchell** [comment]
Hi. Have you specified Relation as the curve type instead of Function? For the default (Function) there should be only one Y value for each A value, consistent with the definition.

**Comment by wilthan** [comment]
Hi,
no, I have not. I marked single points and was not aware that it treats it
like a function. Also, the export option RAW suggested to me that it would
take all points on the plot.
I'll test with the different options you suggested.

tia
boris

**Comment by wilthan** [comment]
Well,
as so many times, it was a user error.
I had no idea that this option exists and what the default assumes.
thx - problem solved!
boris

**Comment by markummitchell** [comment]
Great. And I will see if I can make this behavior more clear.
