### ISSUE TITLE
OS X: Can't launch - to be distributed from App Store

### ISSUE THREAD

**Issue by HarryDymond** [markummitchell/engauge-digitizer#122]
Attempting to launch on OS X 10.9.5 results in the following error dialogue from OS X:

"engauge cannot be opened because of a problem"

The dialogue has a "Show details" button, which reveals (amongst other things):

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/qt5/5.5.1_2/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/engauge.app/Contents/Frameworks/QtHelp.framework/Versions/5/QtHelp
  Reason: image not found

**Comment by markummitchell** [comment]
Looks like it is not loading from the correct directory. I will investigate later today.

**Comment by markummitchell** [comment]
To get around Gatekeeper issues, I tried to make Engauge into an app store package. However, the Xcode and iTunes Connect ecosystem was such a struggle that I will have to wait until an expert volunteers. I am seriously concerned for the future of Apple, after having this experience.

**Comment by HarryDymond** [comment]
Hi Mark,

Thank you for your efforts. Unfortunately I’m not an expert here so can’t offer any assistance.

However, I would say that I am aware that meeting app-store requirements is often onerous or indeed impossible depending on what you want your app to do. For the time being, from my perspective having an app that will launch, even if gatekeeper gives me warnings about it so I have to right-click to open the app on first launch, is much preferable to having nothing at all. (See the "How to open an app from a unidentified developer and exempt it from Gatekeeper” section of this Apple Support doc: https://support.apple.com/en-gb/HT202491).

**Comment by barrypress** [comment]
This seems like too simple answer to really help, but I'll ask anyway because it's important. Have you looked into statically blinking those libraries directly into the application rather than as dynamic libraries?

**Comment by markummitchell** [comment]
Versions 7.2 and later are released through the App Store
