### ISSUE TITLE
Please bring back Grid Lines

### ISSUE THREAD

**Issue by fuquaj27** [markummitchell/engauge-digitizer#123]
In previous versions it was possible to turn on "Gridlines Display", it was also possible to adjust and customize the Grid Display.  This can be an extremely useful tool for my data capture duties.  Unfortunately, in the 7.2 version this feature seems to have been removed.  Pleas bring it back.  I would like to use the newest version due to some great improvements but I can not give up this tool.

**Comment by markummitchell** [comment]
It would help if I had a better understanding of how the grid lines would help. The axis checker provides feedback to verify correct coordinates, and the cursor coordinates are displayed in the status bar. I had thought the grid lines would no longer be necessary

**Comment by fuquaj27** [comment]
I am frequently digitizing figures and plots from articles that are quite old, as such the quality of the initial plot and the condition of the image is often in poor shape.  Sometimes I am working with images that are up to 100+ years old and/or skewed and stretched from the original dimensions.  I would frequently turn on the grid lines to allow me to tweak and adjust my axis points to best fit the whole image and not just the end points.  Also, sometimes I will line up the grid lines to match a portion of the plot and export that section then adjust to grid lines to fit the next section of the plot and export that section.  This ability is very useful when the image has been distorted or stretched.  It allows me to capture the data much more accurately instead of just assuming that all of the intermediate points are lining up as they should.  Your 7.2 version would be just fine for our purposes if all of our plots were in good shape with accurate and proportional axis scales, but in our work that is not always the case.

**Comment by markummitchell** [comment]
That is a great reason for adding grid display. I've started working on it, and expect it to be in a new release in about 2 weeks.

**Comment by fuquaj27** [comment]
This will be a much appreciated feature to have back.  I am looking forward to using the newest version with this function.  Thank you for your prompt and responsive attention to this.

**Comment by markummitchell** [comment]
Grid lines work for version 8.0, which will not be released for a few days just in case something else comes along that requires a change to the saved-file format. The grid lines upgrade is incompatible with current version 7.2
