### ISSUE TITLE
Zoom behavior - zoom in on cursor position instead of center of plot

### ISSUE THREAD

**Issue by wilthan** [markummitchell/engauge-digitizer#124]
Can the zoom with mouse wheel be adjusted (permanent or as additional option) to zoom in on the cursor position instead the center of the diagram?
It would eliminate additional scrolling (up/down - to the side) to get back to where one wants to digitize points after zooming in.

**Comment by markummitchell** [comment]
Great idea, and easy to implement. This will be in the next release.
