### ISSUE TITLE
Multiple coordinate systems crash when curve names differ

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#127]
-----------------Original description-------------
Using multiple coordinate system (2 in fact), the program crashed when I try to switch from one system to another.

To reproduce the bug:

    Import (advance) with 2 coordinate systems
    For system 1, curve is named curve1 (default)
    For system 2, curve is named curve2 for example (the program does not crashed if I let also curve1)
    I create the reference axes and digitize curve for system 1, curve 1
    Try to switch to system 2 and the program crash 

I have tested the versions below and encountered the same problem.

    digit-exe-windows-32-bit-without-installer-file-7_2.zip
    digit-exe-windows-32-bit-installer-7_2.msi
    digit-exe-universal-linux-32-bit-without-installation.AppImage 

------Simpler test---------
+Import(Advanced) with 2 coordinate systems
+Select Add/Remove Curves in coordinate system 1, and rename Curve1 to Curve2
+In the Coordinate System toolbar, switch to coordinate system 2
+Crash

**Comment by markummitchell** [comment]
This fix will be released in version 8.

**Comment by crayxt** [comment]
That's what I call progress!

**Comment by markummitchell** [comment]
Thanks...
