### ISSUE TITLE
Decimal point

### ISSUE THREAD

**Issue by meouda** [markummitchell/engauge-digitizer#128]
I can't enter axis values with decimal places (e.g. 0.06). I am using version 7.2

**Comment by markummitchell** [comment]
Please check Settings/Main Window/Locale. That might be set to Finnish, which does not allow periods (or some language like that). If changing the language fixes the problem, please let me know and I will let others know.

**Comment by meouda** [comment]
Yes, indeed it does. My old setting was set to Arabic, after changing it to English it is now working. Thanks for making this tool available for everyone,
Best regards.

**Comment by markummitchell** [comment]
I imagine this could be very challenging for users who experience it. So, I added a hint to the dialog editing box. That hint, plus the hints in the status text for each of the number boxes, will hopefully prevent this in the future.
