### ISSUE TITLE
Crash due to point ordering problem

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#129]
The symptom is a crash where the dig file has multiple points with the same 'ordinal' value (which is typically 0).

**Comment by markummitchell** [comment]
Fixed in version 8.1. My apologies to those who had to suffer until now. 

The fix was enabled by the insight that a "guard" should be added to the Cmd classes to verify that the Document state was as expected before/after each Redo and Undo. That led to capturing the Document state for each Cmd class that affected the Document Points. Then testing required the creation of virtual 'redo/undo' commands. This was not a one line fix.

**Comment by ucasbusiniao** [comment]
I just updated to the latest version today, the software crashed every time just when I switch to point match tool after I finished defining xy coordinate. Can anyone help with this? Thanks in advance. The alert is as below,
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
