### ISSUE TITLE
Generate graph

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#131]
i\It would be awesome if the program could also generate a formula which represents the graph.

**Comment by crayxt** [comment]
is it even possible?

**Comment by markummitchell** [comment]
I was thinking about a postprocessor tool. We could provide a selection of polynomial, log and other basic equations and then fit the coefficients. With an option for importing custom equations in standard math format(s). Then fit the coefficients. Less elegant than implementation in Engauge but keeps the Engauge interface clean and simple. Thoughts?

**Comment by cweidenhaupt** [comment]
Hi. Thanks for adding the issue. Not sure how engauge actually works, but I assume it generates some kind of equation internally (polynomial?) to display the graph and values. If this equation could be exported in a standard format (e.g. using the Gnuplot format or something similar) it could be used in other programs, to create and analyze the graph. Also, a postprocessor xould be used to provide different formats as well: to use the formula in mathcad, matlab, scilab or even in Excel.

**Comment by markummitchell** [comment]
Engauge applies cubic splines between curve points when the 'smooth' attribute is selected for a curve. Except when drawing or interpolating points during export, each curve is defined and handled as just a set of two-dimensional points (the ones you see in the main window). Any postprocessing tool should probably help the user, or automatically identify, which specific curve types (linear, quadratic, trig, ...) are best applied to a set of points, with appropriate figures of merit to quantify that fit (mean-squared error, ...). The whole process is complicated enough that adding it directly to Engauge would probably make the Engauge interface too complicated for most users.

**Comment by jksmurf** [comment]
+1 for this enhancement. To date I have been exporting data points to Excel, re-creating the graphs and curve fitting using Excel 6th order polynomials or whatever graph type fits best.

**Comment by jkulesza** [comment]
+1; #8

**Comment by markummitchell** [comment]
The first implementation does linear regression with polynomials up to order 7. 

Later on the code may be enhanced with faster algorithms (like LU decomposition versus Cramers rule) or fitting to non-polynomial curves if there really is a need for that.

This can be tested on Windows machines right away (=prerelease) by going to https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master, selecting Release or Debug build and opening the artifacts page.

**Comment by jksmurf** [comment]
Hi mark, just tried it on the graph I sent you for issue #196.
After I worked out how to toggle between curves using green curve generation, it seems the red line (best fit) curve that appears is way out of whack?

**Comment by markummitchell** [comment]
Thanks for the feedback. I'll look into that

**Comment by markummitchell** [comment]
Turns out the log(x) does not equal 10^x. Engauge should work for your input in issue #196

**Comment by jksmurf** [comment]
Brilliant! I love the way you can scroll up and down the polynomial order until you get the best R2 too (or goes out of whack so you can then back off one). The only thing I found tedious is to copy / paste each index before the log10(X)^n function (especially for 7th order) functions, into Excel, then concatenate the formula. Would it be possible to ask for an export polynomial equation function (or at least copy paste all the indices at once?

I am not sure if this should be here or in another issue (request but let me know, I will open a new thread). If not, on the "Curve/Add Remove" dialog window I have a small requests for that Window: Add ability to: 1. Move curves up or Down (order them) 2. Rename the curves.

Also in settings - increase default number of  curves per graph.

Thanks again, awesome prog!
[EngaugeCheck.zip](https://github.com/markummitchell/engauge-digitizer/files/585234/EngaugeCheck.zip)

**Comment by markummitchell** [comment]
The Fitting Window and Geometry Window tables now support click-and-drag for selecting a range of cells when the default settings are used. Note that the Copy menu option is now part of the process (although the Control-C shortcut makes things faster). 

There is also a new 'Enable drag and drop' flag in the Main Window settings. When this is on, click-and-drag in the Fitting/Geometry window tables initiates the dragging process. Since click-and-drag is no longer available for selecting a range of cells, in this mode a range is selected instead using Click and Shift+Click.

Copy-and-paste and drag-and-drop can go to spreadsheets or text editors.

The 'Curve/Add Remove' dialog allows drag-and-drop for reordering the curves. Click on a curve to edit its name.

The default number of curves per graph should have been addressed by the Save As Default button in the 'Curve/Add Remove' dialog. I will create a new issue for this bug.

**Comment by jksmurf** [comment]
Awesome, thanks again, Can't believe how quick you get these worked out. k.

**Comment by markummitchell** [comment]
You're welcome. I now understand how fitting can be useful in Engauge thanks to your request

**Comment by jksmurf** [comment]
Hi I think a small error may have been introduced, the R2, mean Square Error information in the dialog boxes is not there?
![meansquareerrorgone](https://cloud.githubusercontent.com/assets/23158634/20249854/5a2c8b64-aa3d-11e6-9c3b-a581ae1e642f.jpg)

Separately, although I downloaded the branch update after issue #199 had been resolved, when I (a) renamed and then (b) reordered the curves, the curves for those two lines disappeared?

**Comment by markummitchell** [comment]
The empty fields are fixed now. There is a new issue #200 for fixing the points after a curve name has been moved in the Add/Remove dialog.

**Comment by markummitchell** [comment]
Probably should be closed at this point.

**Comment by klaic** [comment]
what is the best export config to export data points to matlab 7? i'm working with a stress-strain graph

**Comment by markummitchell** [comment]
If you just have numbers then using "comma-separated value" (CSV) format
should be fine. If you have one or more column names with a comma then the
better format is "tab separated values" (TSV) format. Please note that I do
not use matlab and cannot test to make sure these work.

The other considerations are whether or not you want raw data points or
interpolated data points, and whether you want all curves on each line or a
separate section in the file for each curve. I do not really have any
guidance for these decisions.

**Comment by klaic** [comment]
an advice for portuguese speakers: export the file to matlab works if Engauge locale is an "English/(...)" location. this is because English system uses dots to separate decimals, as well as matlab (the system working with portuguese language uses commas, and on matlab commas have some other functions)

**Comment by markummitchell** [comment]
That is good to know - I will document that. 

I am wondering if matlab also has a Portuguese local setting.
