### ISSUE TITLE
PDF import

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#133]
Hi,
Most of graphs I work with come in PDF files. So I convert pdf2png first, and then process resulting PNG images.
Now how much effort is required to extend Engauge with poppler library to be able to import specified pages from PDF's, converting them to PNG during the import? Is it something too much to ask from digitizer? Please treat this with lowest priority.
Thanks and congrats on new release. I couldn't imagine even last year how fast development will be.

**Comment by markummitchell** [comment]
You're very welcome. BTW, there's a new 'poppler' branch with pdf support. I'll merge after some more testing.

**Comment by markummitchell** [comment]
This work was a good excuse to fix up the jpeg2000 image import while adding pdf image import. The new code is merged into the master branch. There is a Main Window setting for the resolution so users can balance resolution and image size. Done!

**Comment by crayxt** [comment]
@markummitchell Is the poppler library present in appveryor builds?

**Comment by crayxt** [comment]
@markummitchell Which poppler library you used? I want to use it on appveyor builds

**Comment by markummitchell** [comment]
I first built with version 0.24.4 in the ubuntu package. I realized that was old so I just built with version 0.44.0 and it was a drop-in replacement for the old version. Assuming no problems building in Windows, or any other issues, I'll probably stick with the newer version.

**Comment by crayxt** [comment]
@markummitchell Let me have this issue open until I add poppler support to appveyor builds

**Comment by crayxt** [comment]
From what I see, building poppler library for Windows is very complex task. Don't know whether it will work properly with VS builds. So closing for now, thanks
