### ISSUE TITLE
Focus should be set on new curve in Curve Add/Remove window

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#134]
When you add a new curve in Curve Add/Remove window, focus isn't automatically set on that added curve. So basically I add a curve, press F2 to rename it, but focus is still on curve that was selected before. So I had to click on a new curve manually and then rename it.

**Comment by crayxt** [comment]
Likewise, when curve is deleted, focus must be set on a curve that is previous in list. If first curve deleted, focus must be set to a new first curve.

**Comment by markummitchell** [comment]
The fix is working except for an issue with dragging. Once it's working and tests out fine I will check in the fix.

**Comment by markummitchell** [comment]
Seems to be working.

**Comment by crayxt** [comment]
Confirmed
