### ISSUE TITLE
interpolate over y limit is broken

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#137]
Just noticed, after processing and exporting a bunch of graphs, that interpolation of lines is changed since 5.2
![interpolate-example](https://cloud.githubusercontent.com/assets/33132/16002107/41dd0f9e-316f-11e6-97aa-d9598b89fc77.png)
Here is the example image. X axe max value is 6 and Y max value is 2. I prepared dig file in engauge 5.2. So I mark curves as shown in blue circles
![interpolate-example-points](https://cloud.githubusercontent.com/assets/33132/16002180/a80278cc-316f-11e6-9959-d092f7996939.png)

I expect the Red curve to be extrapolated to 3 at X=3. It is so in Engauge 5.2, but in Engauge 8.2, max value of red curve is limited to value of blue circle at y=2, x=2.2. Why is the interpolation behaviour changed?
Export of Engauge 5.2
```
x,green,red
0.020595,-4.62289e-05,0.0469913
0.02746,0.00118599,0.0538104
0.947368,0.166304,0.96757
1.99771,0.354833,2.00225
2.91076,0.518719,2.90168
5.96568,1.04385,5.91104
```

Export of Engauge 8.2
```
x,green,red
0.0206,-5e-05,0.0538
0.0275,0.0012,0.0538
0.9474,0.1663,0.9676
1.9977,0.3548,2.0022
2.9108,0.5187,2.0022
5.9657,1.0438,2.0022
```
See the last values of red being equal to 2.0022 several times? Dig file is attached, rename from txt to dig

[interpolate-example.dig.txt](https://github.com/markummitchell/engauge-digitizer/files/311518/interpolate-example.dig.txt)

**Comment by markummitchell** [comment]
After nominating this submission as the most specific and well-defined error report ever, I can only hope the solution will be of similar quality :)

**Comment by crayxt** [comment]
If it is easy to fix I could wait, but if not, I have to re-process around 10-15 graphs with several lines each (

**Comment by markummitchell** [comment]
I should be able to fix this in the next 12 hours

**Comment by crayxt** [comment]
No worries, I re-processed graphs which had lines over y limit already. But still, working in Engauge 8.2 is much nicer than in 5.2 (but it was also very good release).

**Comment by markummitchell** [comment]
Seems to be working. I've added the 'extrapolation' regression test for this issue.

**Comment by crayxt** [comment]
When I open example file above, In settings-export format, I still see the 2.0022 several times. so those points are not re-calculated by default?

**Comment by markummitchell** [comment]
The fix has now been copied from smooth-functions to straight-functions (which applies to your DIG file test case), with a corresponding test case. I will also apply it to smooth-relations and straight-relations as part of this issue before calling it finished.

**Comment by markummitchell** [comment]
Tests are now in for all 4 combinations of functions/relations and smooth/straight. I think this is done now.

**Comment by crayxt** [comment]
confirmed, thanks
