### ISSUE TITLE
pdf import process

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#147]
Just tested PDF import feature with page selection.
1) The preview window should retain page aspect ratio - it has page stretched to square currently.
2) when selecting required page via entering number directly, the cursor changes to 'loading' state (in Windows 7 it is rotating circle) and stays in that form even when I press OK and load the document. Moreover, when you save that document and open it again, cursor again changes to 'loading' state.

**Comment by markummitchell** [comment]
For various reasons I had to upgrade to Windows 10. That, and the fact that I am about to switch to the Microsoft compiler mean it may be a couple of days before I can work on this. I still have my old Windows 8 around if Windows 10 cannot build for older operating systems.

**Comment by markummitchell** [comment]
Aspect ratio is now preserved. I have a hack that restores the normal cursor when Ok is pressed, but that is untested since I do not see the problem in Windows 10.

**Comment by markummitchell** [comment]
I was able to reproduce the busy-cursor problem. I think the problem is that clicking on the Ok or Cancel button before the preview calculations would remove the dialog without restoring the normal cursor. The code has been fixed.
