### ISSUE TITLE
What happened to the Curve and Measurement Geometry Windows?

### ISSUE THREAD

**Issue by drmes** [markummitchell/engauge-digitizer#153]
I can't find a way to open the Curve and Measurement Geometry windows. Will they be coming back? They are still referenced in the help.

**Comment by chriddy** [comment]
Same Problem here, Version 8.2 on Windows 7 64bit, laptopt with external monitor. Running with the -reset option as described in

http://digitizer.sourceforge.net/usermanual/answernowindow.html

does not help. Turning off the laptop screen doesn't either.

**Comment by markummitchell** [comment]
@chriddy Your issue is similar in name to the 'missing Measurement' issue, but the two problems are different so I am creating a separate issue 'Window is off screen problem' for your issue.

**Comment by markummitchell** [comment]
I think I can add a geometry window.

**Comment by markummitchell** [comment]
Added. Probably will be released within a couple of days as version 9

**Comment by chriddy** [comment]
Excellent, thanks Mark! I just got version 9 and the geometry window came up after selecting "View -> Geometry window", I did not need to use the "-reset" option.

One more question, though: could you add an option to copy to the system clipboard from the geometry window? I think this was possible in an earlier version and it is often more convenient than exporting to a file first.
