### ISSUE TITLE
Import Image Replace menu option

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#154]
Add menu option for keeping the current document but replacing the image in the background. This can be useful when working on many images that all have the same, or almost the same, settings.

**Comment by crayxt** [comment]
When imported, new image is placed in front, and axes/curves are invisible behind the new image.

**Comment by crayxt** [comment]
Is there any option to adjust imported image to match existing axes?

**Comment by markummitchell** [comment]
In linux the new image is correctly placed, and I do not have windows running yet for testing. However, I checked in a possible fix.

There is no option to automatically adjust axes. That would be a major upgrade.

**Comment by crayxt** [comment]
I'll test as soon as appveryour build is ready. By the way, what is your plan to move windows releases to MSVC?

**Comment by crayxt** [comment]
Nope, still the same.

**Comment by markummitchell** [comment]
I am using the same steps as in the appveyor script, with the same compiler. I am not familiar with the 'ps:gc' step though. But the script and pre-built libraries are excellent and have saved days of work

**Comment by crayxt** [comment]
@markummitchell 'ps:gc' is a powershelll equivalent of ```sed```

**Comment by crayxt** [comment]
@markummitchell By saying that 'axes/curves are invisible behind the new image` I meant that points of axes/curves are visible, but there are no connection lines between them.

**Comment by markummitchell** [comment]
I am not able to reproduce the problem in either Windows or Linux, using the following steps: 1) Import image_replace_1.png 2) Create 3 axis points 3) Create points along the curve 4) Import (Image Replace) with image_replace_2.png. The curves and points all appear in front of the background as expected. Are you doing something different?

**Comment by crayxt** [comment]
@markummitchell I was using example dig file from https://github.com/markummitchell/engauge-digitizer/issues/137
After loading, I replaced its background with standard image from Windows Pictures folder

**Comment by markummitchell** [comment]
The line colors in the dig file from #137 are Transparent.

**Comment by crayxt** [comment]
@markummitchell Ok, I confirm that setting a color for a curve helped. But why it is not possible to make Axe non-transparent?

**Comment by markummitchell** [comment]
The transparent curve for the Axes was meant to be more simple for users. Since 2 of the 3 points often have the same A value, any Axes curve would have to be drawn as a Relation, which could be confusing for those who only see/understand Functions in Engauge. Specifically, a Relation curve through axes points would be smooth (using existing code) resulting in a unfamiliar "rounded L" shape. Also, the Axes Checker highlights the axes points, so adding a curve to make them visible is less critical.

**Comment by crayxt** [comment]
Do we have an option to fine position imported replacement image? To match axes points, at least

**Comment by markummitchell** [comment]
Engauge only has manual adjustment, but that should only take a few seconds for good accuracy, and a few more seconds for excellent accuracy.

**Comment by k1moradi** [comment]
Importing and replacing a new image, Engauge askes me for a new file name on save command, which is annoying. If someone wants to make a new file, they can choose one of the other import options.

**Comment by markummitchell** [comment]
The last post is now issue #332
