### ISSUE TITLE
manual adjustment of points

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#156]
1) Sometimes there are lines lying directly on axes. Regardless of how precise I am in marking such line, there could be close to 0, but still, a little difference.
2) If my digitized image has 100% verical/horizontal axes, how could I verify that the points I marked on both sides of such axe, have the same X or Y value?

**Comment by crayxt** [comment]
Currently I am checking directly in DIG file.

**Comment by markummitchell** [comment]
Do you think that drawing horizontal and vertical lines from the center of the cursor would help? Those lines would be in the graph coordinates versus the screen coordinates (to line up with the underlying background). The lines could be drawn after a delay.

**Comment by crayxt** [comment]
@markummitchell I think when you select some point, in toolbar somehwere there should be an option to manually enter/adjust coordinates of that point. Not sure how you could select one of two points having the same coordinates though (say, when line crosses 0,0 point).
Or, which I think is less precise, is to allow new points to 'snap' to existing points, when you are clicking within specific radius from existing point.

**Comment by markummitchell** [comment]
Similar to an axis pount, the user could right click on a curve point to edit the graph coordinates. The screen position would then be adjusted accordingly (since only the screen position is tracked for curve points). The only danger would be the user entering wrong coordinates that would move the point far away (even off screen) so feedback would be provided in that situation

**Comment by crayxt** [comment]
@markummitchell Is it already implemented for curve points? Doesn't seem to work.
Then, showing a dialog by right click is not quite intuitive - right click is for context menus, which we don't have here. I suggest showing the dialog by double click (Or, in addition, <Enter>, when curve/axis point is selected).

**Comment by markummitchell** [comment]
The new code is on a new branch, and is not working yet.Selecting curve points will be like currently selecting axis points. One or more curve points will be edited at once, with the unedited coordinate left unchanged.

**Comment by markummitchell** [comment]
@crayxt Are you able to try this new code? It is merged into the master branch and is (hopefully) ready for use.

**Comment by crayxt** [comment]
I will be able to test it not earlier than next weekend. Thanks

**Comment by crayxt** [comment]
I tested it and it seems to be working well

**Comment by markummitchell** [comment]
Thanks. I'm sure you are busy, and  appreciate your taking the time
