### ISSUE TITLE
engauge.log is left in ZIP for Windows release 8.3

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#157]
@markummitchell 
https://github.com/markummitchell/engauge-digitizer/releases/tag/v8.3
https://github.com/markummitchell/engauge-digitizer/releases/download/v8.3/digit-exe-windows-32-bit-without-installer-file-8.3.zip

I suggest removing it in build .bat file

**Comment by markummitchell** [comment]
I should mention that project log4cpp_null is a drop-in replacement for log4cpp, that never writes a log file. It was created to keep the OSX sandbox happy, and is now used by the windows build script for Engauge.
