### ISSUE TITLE
Program not responding when changing cooridnate scale

### ISSUE THREAD

**Issue by bartlettD** [markummitchell/engauge-digitizer#159]
When I try to change coordinate scale after setting my axis points the program stops responding, my CPU usage spikes and I have to close the program.
This only seems to occur **after** I have set the axis points.
Attached is my project file where the error occurs.

Ver:8.3
OS:Windows 7 x64
[OPA172_Zo.zip](https://github.com/markummitchell/engauge-digitizer/files/354921/OPA172_Zo.zip)

**Comment by TobiasWinchen** [comment]
I can reproduce this bug in engauge 8.3 on Debian/GNULinux, with the following steps:
 * Open provided .dig file
 * Selecting Setting -> Coordinates 
 * Changing scale to linear for X-Coordinate. 
 * Pressing OK results in high CPU, program freezes

Changing only the Y-Coordinate does not affect the program. Note the large range of the X-axis values.
