### ISSUE TITLE
There is no Document.h in libpoppler-qt5-dev

### ISSUE THREAD

**Issue by zhouhaodada** [markummitchell/engauge-digitizer#160]
As described in engague.h:
2) POPPLER_INCLUDE environment variable pointing to directory containing Document.h
While libpoppler-qt5-dev did not contain Document.h

**Comment by markummitchell** [comment]
Engauge is currently built with version 0.44.0 of Poppler, but Ubuntu uses versions of Poppler as old as 0.24.5. You may need to download a newer version of Poppler and use that instead of the package supplied by Ubuntu.

**Comment by crayxt** [comment]
@markummitchell I can't find Document.h too https://cgit.freedesktop.org/poppler/poppler/tree/qt5/src or https://cgit.freedesktop.org/poppler/poppler/tree/poppler

**Comment by markummitchell** [comment]
@zhouhaodada Thanks for finding this problem. It is fixed now.
