### ISSUE TITLE
Help browser not loading from alternative folders?

### ISSUE THREAD

**Issue by pmendes** [markummitchell/engauge-digitizer#163]
I'm writing a slackware package for your software (slackbuild), and I am trying to put the help file engauge.qhc in /usr/share/engauge-digitizer/engaguge.qhc. I've added this as an alternative path in Help/HelpWindow.cpp, however the resulting binary does not find this file. It also does not find it if I put it in the alternatives that you already have (eg: /usr/share/engauge-digitizer-doc/engauge.qhc). So I am suspecting that the code is actually not looking for these paths. Is there something I am not understanding? (I don't know much about QT, so this is a strong possibility)

Also, as a request, it would be great if you could include the alternative path /usr/share/engauge-digitizer/engaguge.qhc in future releases, as this would allow me to get rid of patching your code.

thanks

**Comment by pmendes** [comment]
Ok, I just found out the issue, I was only copying engauge.qhc to /usr/share/engauge-digitizer/ and I realize now that I need to copy also engauge.qch . So now everything works.  

The request to add this alternate path still holds. If you do so, I can package the whole thing without the small patch file that I am using now.

I will soon upload an updated version to SlackBuilds.org using version 8.3 as the latest I have there is still using version 5.2 (and you no longer make that source available on sourceforge).

thanks

**Comment by TobiasWinchen** [comment]
Hi,

On Wednesday 13 July 2016 19:28:20 Pedro Mendes wrote:
> The request to add this alternate path still holds. If you do so, I can
> package the whole thing without the small patch file that I am using now.

A future-proof and more platform independent method would be to specify an 
additional custom path with a define during configuration. What do you think?

Cheers,


Tobi

**Comment by markummitchell** [comment]
Thanks for your help! And I like the idea of the additional custom path. I'll add it

**Comment by markummitchell** [comment]
You can define a help file path using the HELPDIR variable. This is described in the engauge.pro file. I just successfully tested this using  the line 'qmake DEFINES+=HELPDIR=$HOME/temp engauge.pro'. Moving the help files to my $HOME/temp worked fine. This feature was already available but I had forgotten about it.

**Comment by markummitchell** [comment]
Released in version 9
