### ISSUE TITLE
pdf crop / page select unintuitive

### ISSUE THREAD

**Issue by TobiasWinchen** [markummitchell/engauge-digitizer#166]
Opening a multi page pdf now shows only the first page per default. To use a different page, the user has to change the default settings and open the file again to be able to select a page (at least I didn't found an other way). IMO this is not intuitive. I would suggest: 
 * Show page select / crop dialog as default for multi-page pdf
 * Add a button `crop/page select' that opens the dialog for the current image

**Comment by markummitchell** [comment]
My fault. At one point the default was correct but it somehow was changed to the wrong (unintuitive) value.

**Comment by markummitchell** [comment]
The default is fixed in version 9.1. Allowing editing of the picture within Engage would take a lot of time.
