### ISSUE TITLE
Enhancement request: interpolate X at equally-spaced Y-values

### ISSUE THREAD

**Issue by tedyapo** [markummitchell/engauge-digitizer#170]
Sometimes the graph you have has axes opposite of how you want - like digitizing a current vs voltage curve instead of a voltage vs current.  It's easy enough to post-process and re-interpolate, but it would be convenient to be able to do this within the program (where the graph is invertible, i.e. single-valued at each y-coordinate)

I guess I could also rotate the image externally before digitization.

**Comment by markummitchell** [comment]
Sorry, but adding this would cause a lot of complications in the code, and in the user interface. There are already special cases for Functions versus Relations, Linear versus Logarithmic, and Cartesian versus Polar. Even the documentation would have to be changed. As you mention, the easy workaround is to just rotate the plot. I agree that solution is not very elegant - the rotated text may be hard to read for example.
