### ISSUE TITLE
How to cite engauge digitizer

### ISSUE THREAD

**Issue by fabianrost84** [markummitchell/engauge-digitizer#171]
I used engauge digitizer and now I'd like to cite it (at least refer to it). I could of course simply use the link to the project page (https://markummitchell.github.io/engauge-digitizer/). Would that be the way?

Maybe https://zenodo.org/ would also be interesting for this project. It offers GitHub integration such that all releases could actually get a DOI. (also see [Making Your Code Citable](https://guides.github.com/activities/citable-code/))

**Comment by markummitchell** [comment]
Thanks for  asking. There are no requirements for citations. The URL should be fine.

I've signed up for zenodo, but there will be no releases for a while. It will be a while before I can add a zenodo badge to the github repository. The project web page will be updated then too.

**Comment by markummitchell** [comment]
Badge has been added for release 9.2
