### ISSUE TITLE
There is a problem to run on a ubuntu 16.04 (64bit)

### ISSUE THREAD

**Issue by sudoyang** [markummitchell/engauge-digitizer#172]
$ ./digit-exe-universal-linux-64-bit-without-installer-9_1.AppImage 
/tmp/.mount_T2ntuy
/tmp/.mount_T2ntuy/usr/bin/engauge.wrapper
/tmp/.mount_T2ntuy/engauge.desktop
/tmp/.mount_T2ntuy/usr/bin/engauge: symbol lookup error: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libunity-gtk-module.so: undefined symbol: g_settings_new

After removing libunity-gtk-module.so, engauge-digitizer can run smoothly. But my gvim needs the .so file at that place.

Thanks!

**Comment by markummitchell** [comment]
Thanks, I will look into this.

**Comment by markummitchell** [comment]
Fixed in AppImage 9.1b release.
