### ISSUE TITLE
Error at application start

### ISSUE THREAD

**Issue by MoloTkos** [markummitchell/engauge-digitizer#178]
After upgrading version there is error with start application.
"there is not some .dll file"
Repairing from installetion file does not help in this case.
os Win7_64
![engauge error](https://cloud.githubusercontent.com/assets/20183575/18229759/b0daae94-72ae-11e6-901a-f2ae542737d3.PNG)

**Comment by crayxt** [comment]
So you probably need Visual C++ redistributables installed https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by MoloTkos** [comment]
Intall this package for 64. It is not help too...

**Comment by MoloTkos** [comment]
Ou! install this package for x86. It is help.

**Comment by MoloTkos** [comment]
Thank you!

**Comment by crayxt** [comment]
This is general issue, easily googleable. glad it helped.
