### ISSUE TITLE
New translations

### ISSUE THREAD

**Issue by MoloTkos** [markummitchell/engauge-digitizer#179]
I finished russian translation on transifex. But now i see that there are some new strings wich I don't remember in translated strings. And I want to ask how to test the translation in application? or when new translation take place in application releases?

**Comment by markummitchell** [comment]
A process has not been set up for the translations. I just tried to use the transifex client to automate uploads and downloads from the transifex website, but that did not go well. For now, I will just manually upload and download the translation files. 

To answer your question about testing the translations, one option is to try building the software yourself. However, that can be very painful, especially if you are not experienced with the Qt toolkit. Alternately, I can build a draft release that would show up on github only for developers that are registered with the Engauge project. If you are interested in a draft release, please let me know which operating system you are using.

**Comment by crayxt** [comment]
I thought it is possible to just 'release' translation file in Qt Linguist, which will covert .ts file to .qm file and just put it where all the translation files are resided.

**Comment by markummitchell** [comment]
There is a transifex client that is meant to upload and download files from the transifex website. Better than web scraping. The documentation is very brief and the client displays no output if there is a problem, so setup may take a while.

**Comment by crayxt** [comment]
There is another platform - crowdin, it supports Qt translation files and has cli client. Free for open source projects. But I cannot say that it is better that Transifex.

**Comment by markummitchell** [comment]
Version 9.4 has the russian translation. Uf you make any changes, they will appear in the upcoming release 9.5

**Comment by markummitchell** [comment]
I have set a process for refreshing the translations
