### ISSUE TITLE
missing MSVCP120.dll、MSVCR120.dll

### ISSUE THREAD

**Issue by silaoA** [markummitchell/engauge-digitizer#181]
I download the windows10-32bit-without-installer version on my windows 10 64bit OS,  a dialog box says "MSVCP120.dll、MSVCR120.dll is missing in the system" when engauge.exe is started.

**Comment by crayxt** [comment]
Hi, this is like https://github.com/markummitchell/engauge-digitizer/issues/178
in your case you need https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by markummitchell** [comment]
Is your problem fixed?

This is a common problem. I will see if there is a better way to help users.

**Comment by crayxt** [comment]
we could avoid linking to runtime libraries,

**Comment by markummitchell** [comment]
I'm working on this now. Yes, I'll check into static linking and other options, if any

**Comment by markummitchell** [comment]
The releases web page now shows a hyperlink to the readme file that explains how to fix issues like #178 and #181

**Comment by crayxt** [comment]
@markummitchell It seems like QT libraries are linked to runtime libraries, so there is not much sense avoiding linking engauge.exe to them. We probably should compile with, say 2013, and ship runtime dlls together.

**Comment by markummitchell** [comment]
Does the build_msi_and_zip.bat file need changes? I am fine with using 2013, and bundling runtime dlls.

**Comment by crayxt** [comment]
yes, you need to include libraries listed in this issue's subject.

BTW, https://github.com/markummitchell/engauge-digitizer/blob/master/dev/windows/build_msi_and_zip.bat#L107
why are you including .lib, not .dll file?
