### ISSUE TITLE
Crash on Windows when changing grid to logarithmic after adding axis points

### ISSUE THREAD

**Issue by Ulrich-Lukas** [markummitchell/engauge-digitizer#182]
Hi,

Engauge Digitizer 9.3 installed on Windows 8.1:
I tried the Windows 7 installer (plus the required extra installed MS Visual C++ Redistributable 2015 package) and also the Windows 10 installer (no MSVC necessary apparently).

Engauge Digitizer works as expected.

Unless I import a graph, /first/ set the axis points (according to the wizard) and /then/ change the grid to logarithmic. This apparently triggers a program crash. (Wild guess because of logarithm properties: Division by zero somewhere?)

Thanks anyways, hope this helps.

**Comment by crayxt** [comment]
thanks for your report. on latest CI build, I experience UI freeze following actions you described.

**Comment by crayxt** [comment]
Same UI freeze in Fedora 25, Engauge 9.3

**Comment by markummitchell** [comment]
Thanks for the information.

The code is now smarter about checking for start/step/stop values for grid lines when log coordinates are in use. Now start values of zero are overridden by the minimum document value, which prevents infinite loops.

**Comment by crayxt** [comment]
I am afraid there is still UI freeze when switching to log coordinates (revision is https://ci.appveyor.com/project/markummitchell/engauge-digitizer/build/1.0.292). Import image, define axes, Settings->Coordinates, X coordinates -> set to Log, Y coordinates -> set to Log, press OK = UI freeze. Switching to Log coordinates succeeds if there are no axes defined yet.

**Comment by markummitchell** [comment]
I added some additional checks that catch bad step values, and also added regression tests. Hopefully this is fixed now.

**Comment by markummitchell** [comment]
Seems ok now
