### ISSUE TITLE
Delete unneeded branches

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#186]
It turns out I cannot delete branches created by me in UI of Github, please delete them

https://github.com/markummitchell/engauge-digitizer/tree/appveyor-poppler-and-debug-fix
https://github.com/markummitchell/engauge-digitizer/tree/qt57-appveyor-fixes

**Comment by markummitchell** [comment]
I went through the options, and there does not seem to be a way for you to delete branches. So I removed them.

**Comment by crayxt** [comment]
Perfect!
