### ISSUE TITLE
Crash on Windows - Application unable to start

### ISSUE THREAD

**Issue by bartlettD** [markummitchell/engauge-digitizer#187]
On Windows, after a fresh install, trying to run the program results in the following error.
![capture](https://cloud.githubusercontent.com/assets/2047912/18847435/1e97a07c-83df-11e6-88a5-039f5b9d4124.PNG)

I have installed the latest visual C++ redist as suggested by the platform issues guide but there may be a dependency that I am still missing.

**Comment by crayxt** [comment]
Are you using correct version, for Windows 7?

**Comment by bartlettD** [comment]
Yes, I am running digit-exe-windows7-32-bit-installer-9.3.exe

**Comment by markummitchell** [comment]
Some help may be at http://answers.microsoft.com/en-us/windows/forum/windows_xp-performance/explorer-exe-application-error-0x0150002/5cb9e279-8417-4f3a-ba21-f33f1c07d1d4?auth=1. There are other web pages that offer to help but they are from unknown people and look dangerous.

By the way, are you running 32 or 64 bits?

**Comment by bartlettD** [comment]
For reference. I installed [Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package MFC Security Update ](https://www.microsoft.com/en-us/download/details.aspx?id=26347) and the program launched.

I am running 64bit but made sure to install the x86 libraries.

**Comment by markummitchell** [comment]
Thanks for describing the fix. I have updated the documentation so others can benefit.
