### ISSUE TITLE
Crash when using point match or segment fill

### ISSUE THREAD

**Issue by stairhill** [markummitchell/engauge-digitizer#189]
Enguage 9.3 crashes when trying to use point match or segment fill tools. Win 7 Enterprise 64bit.  Note that axes should be log but can't set due to previously raised issue 

For some reason I can't attach a zipped dig file so see 1N2818U3_thermal.dig in gitter conversation 28 Sept 2016

**Comment by markummitchell** [comment]
My fixes for #182 may have cleared up this problem also. The test cases I ran worked fine.

**Comment by crayxt** [comment]
I downloaded 9.4 appimage and it still hangs on coordinate switching

**Comment by stairhill** [comment]
Still crashes in exactly the same way for me, used digit-exe-windows7-32-bit-installer-9_4.msi installer

**Comment by markummitchell** [comment]
Yes, 9.4 still has a problem. I'm testing version 9.5 and will release it very soon.

**Comment by crayxt** [comment]
I see progress! While testing debug build from https://ci.appveyor.com/project/markummitchell/engauge-digitizer/build/1.0.305/job/50cwcsldx3d80vsm/artifacts

![engauge-error](https://cloud.githubusercontent.com/assets/33132/19071759/1b167b5e-8a4b-11e6-8073-15225f480250.JPG)

**Comment by markummitchell** [comment]
Which windows distribution were you using? 64 or 32 bits?

**Comment by crayxt** [comment]
64

**Comment by markummitchell** [comment]
Bug #189 should be fixed in version 9.5. 

Issues with 64 bit Windows and DLLs should be added as a separate issue since that is in the AppVeyor build which is not part of the official builds (which seem to be working).

**Comment by markummitchell** [comment]
Seems ok now.
