### ISSUE TITLE
missing MSVCP140.dll in Win7 x64

### ISSUE THREAD

**Issue by AntonGut** [markummitchell/engauge-digitizer#193]
Hello!
The program doesn't start in Win7 x64 complaining about missing MSVCP140.dll. Same for installer and non-installer versions (compiled for x86).
![engauge error](https://cloud.githubusercontent.com/assets/4698157/19479474/30a68b9c-9547-11e6-9bd3-89712ea34f36.png)

Installing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145) per recommendations from [similar issue on stackoverflow](http://stackoverflow.com/questions/32998902/msvcp140-dll-missing) didn't help.

Have to look for another digitizer for the time being...

**Comment by AntonGut** [comment]
Oh, sorry. Should have read the Readme before posting.

**Comment by crayxt** [comment]
@markummitchell I've started packing those VC libs with appveyor builds, see https://github.com/markummitchell/engauge-digitizer/pull/191
