### ISSUE TITLE
Only able to select three coordinate points

### ISSUE THREAD

**Issue by schickimiki** [markummitchell/engauge-digitizer#194]
When importing (advanced) I select 4 axes point counts. But then I am still only able to select 3 points. As the origin of the coordinate system is shifted, this makes it more difficult to extract exact values. I have installed digit-exe-windows7-32-bit-installer-9.5.msi.

**Comment by markummitchell** [comment]
I am having trouble reproducing this problem. Can you attach your file? Also, I would like to verify the steps you went through. Was it as sample as (1) choose 4 axes points and (2) only being able to create 3 axis points. Or did you create some axis points, delete one or more axis points, and then create more axis points?

**Comment by markummitchell** [comment]
When the problem appears, you can also upload an error report by clicking on Control+Shift+E. Then click on ok to upload an error report. This will send your document and the steps that were executed since opening/importing the file.

**Comment by markummitchell** [comment]
This problem cannot be reproduced.
