### ISSUE TITLE
Engauge "Crash on Export" and Crash on "Export Format"

### ISSUE THREAD

**Issue by jksmurf** [markummitchell/engauge-digitizer#196]
Hi Mark

I emailed you on this but then thought I would try posting here so the community benefits as well, in case it is" user error" (most likely!), apologies for the double posting, I just registered with github and found my way around.

I have run across a an issue when trying to export the graph data to a csv file for Excel, specifically it crashes when I choose **"File, Export" or "Settings, Export Format".**

I attach the .dig, the original graph and the log file from the crash. It's a log-log graph with a number of lines - I don't believe any points are outside the axes or less than zero (i.e. -ve).

Thanks a lot,

Kristian

[EngaugeGraphExportCrash.zip](https://github.com/markummitchell/engauge-digitizer/files/560981/EngaugeGraphExportCrash.zip)

**Comment by markummitchell** [comment]
Thanks for the input. I will look into this right away. And, I am sure it is not a user input error.

**Comment by markummitchell** [comment]
I have found the problem. When smoothing is used, there is an extrapolation/interpolation on the points that implicitly assumes the point coordinates are linear versus log.  This can result in extrapolated coordinates that are less than zero which causes the crash. This will take some time to fix and test well, but I would like to finish soon so this is no longer a problem.

**Comment by jksmurf** [comment]
Thanks Mark, appreciate you troubleshooting and finding the cause so quickly, must be a bear to even isolate these issues sometimes. I look forward to the program humming along soon. On the off-chance I tried changing all the curves from Function-Smooth to Function-Straight, but it didn't like that either. I'm sure your fix will cover it all. Cheers k.

**Comment by markummitchell** [comment]
Should be fixed for now. Your test case now works and has been added to the regression tests.

**Comment by jksmurf** [comment]
Cheers Mark, much appreciated. Is there an alpha or beta version somewhere I can download to work with? ta

**Comment by jksmurf** [comment]
Cheers Mark, much appreciated. Is there an alpha or beta version somewhere I can download to work with? ta 

kristian 
----- Original Message -----

**Comment by crayxt** [comment]
@jksmurf If you are on Windows, you can try appimage builds, check https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master, select release or debug build and open the artifacts page.

**Comment by jksmurf** [comment]
Works beautifully. Thank you!

**Comment by markummitchell** [comment]
Glad to help. 

@crayxt I will offer the appveyor builds from now on. Great idea!

**Comment by XtrianaBMS** [comment]
Hi Mark,

I am trying to contact you in relation to your software.  Could you please let me know how to reach out to you directly offline.
Thanks!

**Comment by markummitchell** [comment]
Sure. My first name + "ummitchell" at gmail.
