### ISSUE TITLE
Time values are incorrect when file is saved and reloaded

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#201]
Hi.
When i digitalize a graphic, with the date & time in the asse x, it works fine.
But when I close the program and i reopen my project, the time of points is changed.
For example, for the first point, i put (asse x):
2016/11/16 16:50:12
and reopening the program, the point has:
2016/11/16 17:26:40
Can you help me?
Thank you
Giovanni

**Comment by markummitchell** [comment]
Saved files now have increased resolution so the time values are not corrupted. They need a large dynamic range.

**Comment by markummitchell** [comment]
A prerelease for Windows is available for immediate use, from https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/7oldxrooca6p9mxr/artifacts.

**Comment by crayxt** [comment]
:smiley:
