### ISSUE TITLE
Cannot export the file

### ISSUE THREAD

**Issue by Samuelcgm** [markummitchell/engauge-digitizer#202]
When I try to export the file or press export setup, the software shows an error message and close itself automatically.
![error](https://cloud.githubusercontent.com/assets/23662250/20533476/9d966bfe-b118-11e6-946b-e260cac4b806.png)

**Comment by markummitchell** [comment]
Can you add your DIG file here? I tried to reproduce the problem but could not.

**Comment by Samuelcgm** [comment]
Strange, I cannot upload dig or zip or rar file here...Should I send it directly to your email?

**Comment by markummitchell** [comment]
Looks like the file extension has to be changed from .DIG to .TXT. You can try uploading again, or send to my email.

**Comment by Samuelcgm** [comment]
[Graph 1.txt](https://github.com/markummitchell/engauge-digitizer/files/609488/Graph.1.txt)

**Comment by Samuelcgm** [comment]
Hi, I have tried the engauge digitizer on other computer and I even tried some older versions, but the same problem still occur, do you know why?

**Comment by markummitchell** [comment]
Sorry for the delay. The problem with the data is that at least two points have the same x coordinate, but the curve types are 'Functions'. Functions require every point to have a unique x coordinate. I've checked in a fix so the code can handle this problem, but the real solution is to change the curve types to 'Relations'. In the Settings / Curve Properties dialog, set the curve type for your 3 curves to 'Relations Smooth' or 'Relations Straight'. That should fix the problem. Good luck
