### ISSUE TITLE
Crashes on Fedora 25 (Wayland) after import/open menu command

### ISSUE THREAD

**Issue by giacom0rovers1** [markummitchell/engauge-digitizer#203]
File -> Import 
File -> Import (Advanced)...
File -> Open...

All cause the program to crash with a gnome notification of failure

**Comment by crayxt** [comment]
@giacom0rovers1 try this https://fedoraproject.org/wiki/Common_F25_bugs#Most_QT5_apps_crash_under_Wayland_when_displaying_a_file_dialog_if_you_don.27t_have_qgnomeplatform_installed

**Comment by crayxt** [comment]
```sudo dnf install qgnomeplatform```

**Comment by giacom0rovers1** [comment]
@crayxt  it works great! thank you very much :+1:

**Comment by sagitter** [comment]
This was a packaging issue pratically.
Please, open a bug ticket on https://bugzilla.redhat.com/ next time.

I'm fixing this lack on next packaging release (9.7)

**Comment by markummitchell** [comment]
Thanks for the help. I tried to reproduce the problem with a fresh installation of Fedora 25 but everything worked fine with and without the qgnomeplatform package.

**Comment by crayxt** [comment]
@markummitchell You sure you were running Wayland session?

**Comment by markummitchell** [comment]
Yes, I used the default GNOME session which the documentation states is Wayland. 64 bit operating system. My test may not be useful since at least one person at the wiki link mentioned they had upgraded an older distribution to Fedora 25, and I had a fresh Fedora 25 installation.
