### ISSUE TITLE
Obtain outline / without line between positions!

### ISSUE THREAD

**Issue by aude21** [markummitchell/engauge-digitizer#204]
Hello,

I try to use engauge-digitizer to obtain the x and y positions of my cell outline.

The problem is that automatically, the positions are linked by a line (cf picture), but I don't want to link them this way as I want the outline of the cell.

Thank you very much!
![capture](https://cloud.githubusercontent.com/assets/24287603/20783617/345a4286-b795-11e6-859c-b27bbcdff51a.JPG)

**Comment by markummitchell** [comment]
Under Settings / Curve Properties you can change the 'Connect As' value from Function to Relation. Engauge sorts points in a Function by their X coordinate, as seen in  your picture. Points in a Relation can form the round shape that I think you want. Good luck

**Comment by aude21** [comment]
thank you, it works!!
