### ISSUE TITLE
Qt 5.8 compatibility

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#207]
Needs to be checked. Probably after Qt 5.8 gets added to https://www.appveyor.com/docs/installed-software/#qt

**Comment by markummitchell** [comment]
Engauge builds with Qt 5.8 with and without the pdf and jpeg2000 build options. When AppVeyor supports that version, new 5.8 builds can be added.

**Comment by crayxt** [comment]
I am interested in Qt Lite, which could result in more compact size of compiled program.

**Comment by crayxt** [comment]
It works! Although Qt Lite is meant to reduce size of Qt itself during its build, so not applicable here.
