### ISSUE TITLE
bundle MSVCP140.dll VCRUNTIME140.dll for computers that don't have it?

### ISSUE THREAD

**Issue by cmrdt** [markummitchell/engauge-digitizer#210]
(missing Visual C/C++ Redistributable) but installing runtime requires admin..

**Comment by crayxt** [comment]
Hi, which installation file you are referring to?

**Comment by cmrdt** [comment]
both

digit-exe-windows10-32-bit-without-installer-file-9.8.zip
digit-exe-windows7-32-bit-without-installer-file-9.8.zip

**Comment by markummitchell** [comment]
I am installing VS 2015. Will not be able to finish the transition from VS 2013 today.

**Comment by markummitchell** [comment]
Does it make sense to base windows builds on the log4cpp and fftw files in the new appveyor directory? I could upgrade the build script with an option for 32 or 64 bit builds.

**Comment by crayxt** [comment]
@markummitchell yes it does, since fftw is the official release, and log4cpp is built by me in clean environment. I couldn't make the build link with log4cpp_null's obj file in engauge-digitizer's debug build mode, so I switched back to log4cpp dll files.

**Comment by markummitchell** [comment]
The move to MSVC2015, and including the msvcp140.dll file, tests out fine now

**Comment by markummitchell** [comment]
Need to update build script for 32 bit releases
