### ISSUE TITLE
Export completion message

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#216]
It would be good to have a message with export completion status.

**Comment by markummitchell** [comment]
Is there an application I can look at to see what you are looking for? There could be a message in the status bar, or a modal dialog, or maybe something else.

**Comment by crayxt** [comment]
I can describe the process. So you have DIG file opened, and want to export curves to CSV. To do this you open File-Export, choose the file name, and press OK. After that, you don't have any notifications on the status of export process. Simple dialog window saying that export completed successfully and with OK button could help.

**Comment by markummitchell** [comment]
My personal preference is to not show a modal or modeless dialog box after export, and I know at least a couple of people who would get upset at the interruption. However, I looked around to see what other people thought to learn more, and found some of the same thinking at https://en.wikipedia.org/wiki/Modal_window. Maybe just a message in the status bar?

**Comment by crayxt** [comment]
@markummitchell yes, a message in the status bar should work.

**Comment by markummitchell** [comment]
Fixed?

**Comment by crayxt** [comment]
Yes, thanks
