### ISSUE TITLE
build warnings

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#218]
https://ci.appveyor.com/project/markummitchell/engauge-digitizer/build/1.0.420/job/aes4o0516j2saa75#L199
```
c:\projects\engauge-digitizer\src\callback\callbackupdatetransform.cpp(33) : warning C4715: 'CallbackUpdateTransform::transformIsDefined': not all control paths return a value
```

https://ci.appveyor.com/project/markummitchell/engauge-digitizer/build/1.0.420/job/aes4o0516j2saa75#L532
```
src\Translator\TranslatorContainer.cpp(9): warning C4100: 'app': unreferenced formal parameter
```

**Comment by markummitchell** [comment]
Fixed?

**Comment by crayxt** [comment]
Yes, it seems like it is fixed, I checked the build logs.
