### ISSUE TITLE
Add Suggested, Version Agnostic, Citation to github.io Page

### ISSUE THREAD

**Issue by jkulesza** [markummitchell/engauge-digitizer#220]
It would be helpful to have a suggested citation, not tied to a particular version, given on the http://markummitchell.github.io/engauge-digitizer/ page.  I see citations are available on the DOI page; however, it is troublesome to find citations for past versions.

I currently plan to use in an upcoming report: `Mark Mitchell et al., “Engauge Digitizer Software.” Webpage: http://markummitchell.github.io/engauge-digitizer/. March 2017.`.

**Comment by markummitchell** [comment]
I looked into doing this with Zenodo and did not get encouraging result. Do you have any suggestions?

**Comment by jkulesza** [comment]
If Zenodo cannot accommodate this, I would propose keeping its page the way it is for someone who wants an up-to-date DOI reference.  However, I'd recommend adding a "section" to the http://markummitchell.github.io/engauge-digitizer/ page labeled "Suggested Citation" and the body as "Mark Mitchell et al., “Engauge Digitizer Software.” Webpage: http://markummitchell.github.io/engauge-digitizer/ last accessed [current date]." where [current date] is ideally a calculated field.  Thoughts?

> Thanks for the citation

Thanks for the good work on a *very* helpful tool!

**Comment by markummitchell** [comment]
I made a change to the project page. Is that correct?

**Comment by jkulesza** [comment]
Looks great to me.  Thank you!
