### ISSUE TITLE
Suggestion: Contributors should Provide Real Names

### ISSUE THREAD

**Issue by jkulesza** [markummitchell/engauge-digitizer#221]
Currently, some contributors are listed by their pseudonyms (e.g., The Gitter Badger & badshah400 on https://zenodo.org/record/200196#.WL28SBIrLXQ).  For citation purposes, it would be helpful if these names were known to associate contributions with individuals.  

Some discussion on this with regard to the LyX project (www.lyx.org) is available at http://www.mail-archive.com/lyx-devel@lists.lyx.org/msg195635.html and responses to that subthread.  The resulting (publicly available) permission statement is given at http://www.mail-archive.com/lyx-devel@lists.lyx.org/msg196868.html and credit for the work is given at http://www.lyx.org/Credits.

Some rationale for a project requesting "real names" rather than pseudonyms:

- To be to be resistant to any kind of copyright claims or trolling.  Accepting code from anonymous or obviously fake identities does not help this.
- To acknowledge the source of contributions and to help ensure originality and that credit is given where it is appropriately due.

Thank you for your thoughtful consideration on this point.

**Comment by markummitchell** [comment]
The contributors who only supplied their pseudonyms only edited or added 3 or fewer lines of text each. Issues of copyright claims or trolling would not apply just by visual inspection. In the future I can request real names for contributors, but the past releases cannot be edited. I suggest just including Tobias Winchen, Baurzhan Muftakhidinov and myself as the contributors. I believe everybody involved would be fine with that. I also look to huge projects like the Linux kernel with thousands of contributors - they probably cannot be including every contributor in citations.

**Comment by jkulesza** [comment]
> The contributors who only supplied their pseudonyms only edited or added 3 or fewer lines of text each. Issues of copyright claims or trolling would not apply just by visual inspection. 

Sounds good, thanks for looking into this.

> In the future I can request real names for contributors, but the past releases cannot be edited. 

I understand that past releases cannot (and should not) be edited.  However, I think this would be a good precedent to start moving forward.  With the way online presences have evolved, there is no reason to keep these types of code contributions anonymous.  Hopefully contributors will feel similarly.

> I suggest just including Tobias Winchen, Baurzhan Muftakhidinov and myself as the contributors. I believe everybody involved would be fine with that. 

Sounds good, will do.

> I also look to huge projects like the Linux kernel with thousands of contributors - they probably cannot be including every contributor in citations.

Probably true; however, this simple inclusion is a good way to encourage contribution.  That's why in #220 I used "Mark Mitchell et al." in my citation — because it would be impractical to list everyone.  However, as a point of bookkeeping and recognizing contribution, I wonder if another file like CREDITS in the repository would be a good place to capture individual contributors (in an easier way than culling commit authors).

Thanks for your thoughtful attention to this!

**Comment by markummitchell** [comment]
I think this issue is closed, with changes done for #220. Regarding the CREDITS file, I am using the more public web page instead, especially since that allows hyperlinks to personal pages.

**Comment by markummitchell** [comment]
You can close this if you want.

**Comment by jkulesza** [comment]
I'll close it — I just wanted to bring this up for your consideration.  Thanks for the good discussion.
