### ISSUE TITLE
crashes on OSX

### ISSUE THREAD

**Issue by spookydd** [markummitchell/engauge-digitizer#223]
OSX 10.8.5
engauge 9.7
crashing at the same point every time, when entering the 3rd point for the axis.

**Comment by markummitchell** [comment]
Can you attach your file? In Settings/ Main Window, what is your locale/location?

**Comment by spookydd** [comment]
Hi,

On Mar 27, 2017, at 9:19 PM, Mark Mitchell <notifications@github.com> wrote:

> Can you attach your file? In Settings/ Main Window, what is your locale/location?

It does it even if there was no file saved. I tried again several times, and hoping to get a little further before it crashes, I saved a file before doing anything, then kept saving again at each step, and it always crashes when we click ok after giving the coordinates for the 3rd axis point.

I'll attach what I did last, but keep in mind it did crash with no file made at all.

And it does it regardless of what picture was imported. I tried with different ones, just in case the imported file could be a cause, but it wasn't.

In the setting, at first I did't touch it, so it was whatever the defaults are, then afterwards I looked in there, checked a couple more checkboxes and left everything else as is, so the locale remains as english/us.

As I posted, this is osx 10.8.5, not the latest.


Thanks






-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
Looks like building the app in 10.11.5 causes problems running in 10.8.5. I verified that the download installs and builds fine on my own machine. It will take some time to set up a working build environment, and hopefully fix this. In the meantime, you can use the Windows or (using a LiveDVD) Linux versions.

**Comment by spookydd** [comment]
On Mar 28, 2017, at 8:42 AM, Mark Mitchell <notifications@github.com> wrote:

> Looks like building the app in 10.11.5 causes problems running in 10.8.5. I verified that the download installs and builds fine on my own machine. It will take some time to set up a working build environment, and hopefully fix this. In the meantime, you can use the Windows or (using a LiveDVD) Linux versions.

I don't use windows or linux, so that's not an option.

Is there anything I can do to help?

I should have x-code installed on my mac. Although I'm no mac programmer and I suppose this is written in C or some flavor of it, I am familiar with building C apps on unix, but not the mac.


Thanks


-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
If you could test the final results, that would be very helpful.

**Comment by spookydd** [comment]
On Mar 28, 2017, at 4:46 PM, Mark Mitchell <notifications@github.com> wrote:

> If you could test the final results, that would be very helpful.

Of course I will. That's implied.


Thanks


-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
Sorry, but restrictions on macos installations in virtual machines, an unrequested upgrade to sierra, and toolchain bugs are taking too much time. I am unable to support apple until they provide better support to developers. I will revisit this decision in a year. Until then version 9, which works for yosemite, will be available

**Comment by spookydd** [comment]
Hi,

In the mean time while eventual fixes are found, what are my options on my current osx (10.8.5) for running this tool?

I have a few graphs that I need to process, and I don't know of any other way to do this.


Thanks,


-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
After some research, here are some options in no particular order:
1) Run Live DVD such as Knoppix and run an AppImage release. No installation required, but this uses Linux rather than macOS
2) Option #1 but inside a virtual machine. Files can be shared by the host and guest operating systems.
3) Find a computer that can run MacOS 10.11
4) You can try to build the software yourself with me available for assistance
5) You can share your desktop using TeamViewer, Chrome Remote Desktop, Google Hangouts or Skype and I can help with the build
Does any of these sound good?

**Comment by crayxt** [comment]
there is also http://arohatgi.info/WebPlotDigitizer/

**Comment by spookydd** [comment]
Hi,

On Apr 20, 2017, at 7:46 AM, Mark Mitchell <notifications@github.com> wrote:

> After some research, here are some options in no particular order:
> 
> 	• Run Live DVD such as Knoppix and run an AppImage release. No installation required, but this uses Linux rather than macOS
> 	• Option #1 but inside a virtual machine. Files can be shared by the host and guest operating systems.
> 	• Find a computer that can run MacOS 10.11
> 	• You can try to build the software yourself with me available for assistance
> 	• You can share your desktop using TeamViewer, Chrome Remote Desktop, Google Hangouts or Skype and I can help with the build
> Does any of these sound good?

I've tried a bit the virtualization option, but this isn't very practical and I've had errors as well. I obviously prefer avoiding this kind of thing.
Plus I don't do linux much. (only on web servers)

I can't have other computers running 10.11, I don't have that many and I have older software that won't run on anything newer than what I have, and I need this and can't move on.

I've built a lot of unix software but not on a mac, so although I have occasionally built something, I'm not familiar enough to be certain of a reliable result, so of course assistance would be preferable.

I would favor the option of remote access to build on my machine. I have occasionally used some type of remote access software before, although fairly long ago, there must be something left and probably still usable. I'm thinking about apple's remote desktop, which I think I have used before, but the other way around. Not to build software, but it doesn't make any difference.

Using Skype at the same time would help along too.

To save time, it would be good to make sure the needed software is made common for both sides…

I should have the apple build stuff still in there, even though I haven't used it for a long time, plus I have (rarely) used things like fink and the likes, to get linux/unix stuff added to my machine. Although there were at some point some collisions that broke things.


Thanks,


-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
Excellent. I recommend installing downloading the open source version "qt-unified-mac-x64-2.0.2-2-online.dmg" (or newer than 2.0.2) from www.qt.io. Just specify the open source version and install. Then contact me via skype with the same account name I use here at github plus "@gmail.com". We can set up a meeting time.

**Comment by spookydd** [comment]
Hi,

On Apr 22, 2017, at 9:39 PM, Mark Mitchell <notifications@github.com> wrote:

> Excellent. I recommend installing downloading the open source version "qt-unified-mac-x64-2.0.2-2-online.dmg" (or newer than 2.0.2) from www.qt.io. Just specify the open source version and install. Then contact me via skype with the same account name I use here at github plus "@gmail.com". We can set up a meeting time.

I had never heard of that package, so this is totally new to me.
I grabbed it and it gave me 2.0.5. I assume this would be ok.
I just installed this and skipped over the part where it asked for account credentials, which I don't have and I'm not sure I would need this anyway.
It's right now downloading a bunch of stuff, so I'm not sure what it's really doing. I just chose whatever minimum options I thought would be needed in the installer.
It'll take a while it seems.

What time zone are you in? I am in GMT+1 right now.

I'll try Skype now…


Thanks


-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
I am in GMT-7, and just woke up. The Qt installation appears to be going as expected. I will leave Skype on.

**Comment by markummitchell** [comment]
Just remembered to enable access to my account...

**Comment by spookydd** [comment]
On Apr 23, 2017, at 3:52 PM, Mark Mitchell <notifications@github.com> wrote:

> I am in GMT-7, and just woke up. The Qt installation appears to be going as expected. I will leave Skype on.

Wow! 8 hours of difference. Can make things a bit tricky.

Is that MST or CST? I forgot.

I tried looking you up in Skype using engage-digitizer without success, but I found markummitchell. Since there is only a single hit, I'm guessing that must be you.

After quite some time, perhaps at least a half hour of downloading, the Qt installer failed and gave me this error:




I'm guessing you're more familiar with it than I am and perhaps you have an idea of what's going on.
I'm seeing something about Version, but it says execution failed, so I really don't know what the deal is.


-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
The error is not displayed in your message, but I am guessing it appeared when building the examples. For some reason the default installation process is to spend much time building every example and demo. Sometimes during the example/demo builds a system requirement like OpenGL is not available causing a build error. That is not a problem since the important steps are in the first (roughly) 15 minutes. The time zone is PST, but I am flexible. For my skype account please try (1) my github account name but only the first 9 characters or (2) my github account name plus "@gmail.com"

**Comment by spookydd** [comment]
On Apr 23, 2017, at 5:02 PM, Mark Mitchell <notifications@github.com> wrote:

> The error is not displayed in your message, but I am guessing it appeared when building the examples. For some reason the default installation process is to spend much time building every example and demo. Sometimes during the example/demo builds a system requirement like OpenGL is not available causing a build error. That is not a problem since the important steps are in the first (roughly) 15 minutes.

So I suppose I can just click on ignore and let it be.
I left it as is with the error, until I knew what would be best to do.

> The time zone is PST, but I am flexible. For my Skype account please try (1) my github account name but only the first 9 characters or (2) my github account name plus "@gmail.com"

I figured perhaps it was MST because with the 8 hours of difference, that would be 2 more than for EST.
Anyway, so you're actually in CA, and it's morning for you, evening for me.

I have the wife and kid in the room, each on their own computer and it's a little noisy in the room, so if we Skype shortly, we'll have to manage with text.

I shortened the user name in my Skype lookup and it gave me a different result from earlier, but still a single one. There are no info beyond the usa location and the name, which should be correct, but how can I be sure it's you?


And btw: I clicked on ignore in the Qt installer and it gave an other error:





Am I missing some dependency? It's not explicit, at least to me…


-- 
Didier Godefroy
dg@ulysium.net
Support Anti-Spam legislation
Join the fight http://www.cauce.org

**Comment by markummitchell** [comment]
I think you have the right account. If it was not, the privacy settings would probably let you know. Text chat would be fine. For some reason, the Qt build errors are not appearing in this forum

**Comment by markummitchell** [comment]
This issue was made solvable by the great help of Didier. Currently undergoing testing so Mac releases can be resumed

**Comment by markummitchell** [comment]
Accepted by App Store, downloaded and tested.
