### ISSUE TITLE
Release with Scale Bar feature, v10?

### ISSUE THREAD

**Issue by pedro-ricardo** [markummitchell/engauge-digitizer#224]
Hello there, when are you planning to make the **release** with the recently added Scale Bar feature?

**Comment by markummitchell** [comment]
I will try to make a release today

**Comment by pedro-ricardo** [comment]
Thank you very much!

**Comment by markummitchell** [comment]
Released.

**Comment by markummitchell** [comment]
How is it working for you? If you have no problems, you can close this issue.

**Comment by pedro-ricardo** [comment]
It's working like a charm. Thank's for the quick response. (Tested in Windows7 64bit and Open-Suse 13.2). If i find any weird behaviour, i'll let you know.

**Comment by pedro-ricardo** [comment]
Hello there, maybe I don't know how to turn it on, but **Scale Bar** seems to be missing again in release 10.12.

**Comment by markummitchell** [comment]
Hi Pedro, I have been offline and just got back. For your issue, can you try adding a curve and then changing its type in Curve Properties to Relation/StraightLines? Then View/GeometryWindow should show the geometry. There is a Scale Bar now, but it now has a different meaning - it is used to define the scale in a map.

**Comment by pedro-ricardo** [comment]
Thank you for the quick answer :+1: 

I've tested and if I understood it correctly, that's not a scale bar... That way I can measure a distance between `2 points`. But for that I need to define `2 axis` ... 

Seems like your method assumes that I have that second axis known, like a 2d plot.

The previous Scale Bar feature let me define 1 distance known (the case when a photo has a ruler on it's side or a map with the scale indicated, for example) and then I can measure a distance between points based only on that.

**Comment by pedro-ricardo** [comment]
I'll probably need to folow the same steps you said, but before those I need to be able to define my axis based on 1 distance only.

**Comment by markummitchell** [comment]
Do you have a Scale Bar tool under the Digitize menu? If not, do you remember which installer you downloaded? Your earlier post mentions version 10.12, but maybe something is different between the Windows, Linux and OSX builds.

**Comment by pedro-ricardo** [comment]
It's 10.12 and a Linux distro
![Screenshot_20190330_121015](https://user-images.githubusercontent.com/15893711/55277969-de78f180-52e4-11e9-99a3-365d47bc8a86.png)
The scale bar is axis is grey

**Comment by markummitchell** [comment]
Sorry about the confusion. To get the scale bar active, you have to use Import(Advanced). That changed when a third mode was added in which 4 axis points are used for graphs with unknown X values for Y-axis points and unknown Y values for X-axis points.

**Comment by pedro-ricardo** [comment]
I think this is what you've asked, sry
![Screenshot_20190330_121432](https://user-images.githubusercontent.com/15893711/55278006-74148100-52e5-11e9-93c8-08e873f1e885.png)

**Comment by pedro-ricardo** [comment]
Ok I'll try that

**Comment by pedro-ricardo** [comment]
HA! Found it !!
Thank you very much!

**Comment by markummitchell** [comment]
And I am improving the documentation whenever there is confusion like this (#314). Thanks
