### ISSUE TITLE
License issue for SUSE Legal

### ISSUE THREAD

**Issue by badshah400** [markummitchell/engauge-digitizer#230]
Hi!
I package your excellent software for openSUSE. However, SUSE Legal has recently declined my packages due to the copyright header saying "Distribution requires prior written permission" on the source file  ```src/Callback/CallbackSearchReturn.h``` which seems to be at odds with the application's otherwise GPL-2.0 licensing. The other source files are all consistent with GPL-2.0, and this seems to be the only file that carries additionally the following problematic header:

```
/**
 * \file CallbackSearchReturn.h
 * \brief
 * \copyright Copyright (c) 2012 Mark Mitchell. All rights reserved. Distribution requires prior written permission.
 */
```

Any suggestions for how to get around this, or is this something that indeed needs to be fixed?

Many thanks!

[1] https://build.opensuse.org/request/show/490800

**Comment by markummitchell** [comment]
I removed that comment - easiest fix I've had in years. I'd be glad to look at other changes if you have some.

**Comment by badshah400** [comment]
@markummitchell Thanks a lot for the quick response and fix.
