### ISSUE TITLE
v10 - empty curves throws unrecoverable errors on linux

### ISSUE THREAD

**Issue by holla2040** [markummitchell/engauge-digitizer#233]
1. import an image
2. add a curve, project should now have Curve1 and Curve2
3. add Points to Curve1
4. opening "Export" or "Error Report" throws unrecoverable error
5. adding points to Curve2 fixes this.

[bug.zip](https://github.com/markummitchell/engauge-digitizer/files/1047795/bug.zip)

**Comment by markummitchell** [comment]
This is probably a duplicate of #226, which has been fixed but not released yet. I tested your case in the new version and it worked fine. The new release will be soon.

**Comment by holla2040** [comment]
OK sounds good
