### ISSUE TITLE
Smaller step sizes in zoom factors

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#237]
Zooming by factors of 2 can often result in an image that is too small, and when it is zoomed in by one step can leave the image too big. Zoom increments should be smaller than a factor of 2.

**Comment by oopman2002** [comment]
Just a quick note to give you a thank you for the zoom upgrade. It really helps a lot.

**Comment by markummitchell** [comment]
And by spending the effort to give feedback like this, over 1000 other people a week benefit (github downloads, not including linux distributions).
