### ISSUE TITLE
Automatically sort data with x in ascending order

### ISSUE THREAD

**Issue by Daniel-UCAS** [markummitchell/engauge-digitizer#241]
First, thank you all for this awesome software, it really helps a lot.  
When I use the curve point tool to get data, it will automatically sort data with X in ascending order, is it possible to remain the order as I clicked because my data is not monotone in X?

Best wishes!
Yu

**Comment by markummitchell** [comment]
Hello Yu,
Change the curve type from Function to Relation. Use Settings / Curve
Properties. Then choose 'Relation - Straight' or 'Relation - Smooth'. As
you have seen, the default is 'Function - Smooth'.
Good luck. MarkM

**Comment by Daniel-UCAS** [comment]
Hi MarkM,
That's just what I want, thank you for the fast reply!
BTW, I wonder whether engauge digitizer has a fast automatically curve trace function like [Graph Grabber](https://www.quintessa.org/software/downloads-and-demos/graph-grabber-2.0#download). I follow the procedure [here](http://digitizer.sourceforge.net/usermanual/tutorautopointgraph.html), but it does not function very well since my graph is actually not that clear.
Thank you.
Best wishes. Yu

**Comment by markummitchell** [comment]
Try Settings / Color Filter to make your graph more clear.

**Comment by Daniel-UCAS** [comment]
Yes, that does very good job. Thank you again for the quick reply, I think this community is the most friendly one I had ever met.
I suppose I can close this issue now.
Best wishes!
Yu

**Comment by markummitchell** [comment]
Thank you!
Mark
