### ISSUE TITLE
Polytriarylamine material database for gpvdm

### ISSUE THREAD

**Issue by IsmaelAR** [markummitchell/engauge-digitizer#242]
[ptaa characteristics.pdf](https://github.com/markummitchell/engauge-digitizer/files/1346955/ptaa.characteristics.pdf)

**Comment by markummitchell** [comment]
Hello. Are you asking for support for pdf? If so, which release are you asking about? I will try working on all of them for now.

**Comment by markummitchell** [comment]
Pdf support will only be in linux versions. Adding pdf support in windows is a very complicated process involving the building of many libraries, and some of those libraries are no longer supported.
