### ISSUE TITLE
Decimal comma in csv exports 

### ISSUE THREAD

**Issue by nicorusti** [markummitchell/engauge-digitizer#243]
Decimal values are separated by a comma from their integer part, messing up csv files. 
I think it would be easier to just always use a dot. 
P.S: My OsX default locale (English-Switzerland) uses a dot for decimals, probably the same locale in your libraries behaves differently.

**Comment by dirixmjm** [comment]
Proper CSV files allow to use "," values inside content. It only needs to be quoted properly.
From RFC 4180:
Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

**Comment by markummitchell** [comment]
Thanks dirixmjm!

**Comment by nicorusti** [comment]
Thank you @markummitchell  for the quick patch! Did you also release binaries for Mac?

**Comment by markummitchell** [comment]
There is no publicly available pre-release for Mac, although I could probably use dropbox. Once the changes are verified (by just me or by both of us) then I'll make a regular release. Regular releases have builds for linux, mac, and windows.

**Comment by nicorusti** [comment]
If you could build a pre-release for mac I'll be happy to try it! Sorry, I have no Windows machine available at the moment

**Comment by markummitchell** [comment]
You can find a pre-release at https://drive.google.com/drive/folders/0B5_zuEeNEicQY1U0dFRYWTZqblU?usp=sharing.

**Comment by nicorusti** [comment]
Thank you Mark! 
Now with locale set to English/Switzerland comma separated decimals are correctly enclosed in double quotes. 
An example: 
> x,y_1
> "10,076","0,00185"
> "10,187","0,03044"

**Comment by markummitchell** [comment]
Great. I will make a new release soon.
