### ISSUE TITLE
options for ~/engauge.log

### ISSUE THREAD

**Issue by mianzhi** [markummitchell/engauge-digitizer#246]
Dear contributors,

Thank you very much for this useful tool.
One thing that bothers me is its log file `~/engauge.log`.
I wonder whether I can stop engauge from generating this file?
Or at least use a name like `~/.engauge.log`?
It really pokes my OCD each time viewing/ls my home folder.
Thank you for the consideration.

Best regards,
Mianzhi

**Comment by markummitchell** [comment]
Great suggestion. Since the log files have only been useful for me, I will remove them. Although I feel bad that some people may miss out on the beauty and wonderment that is an Engauge log file.

**Comment by crayxt** [comment]
@markummitchell Hi, maybe you could disable logs by default, but introduce an option in Settings to enable it?

**Comment by markummitchell** [comment]
@crayxt I like that idea. I will look into it, although my first guess is that it may be sufficient to offer a command line option to enable logging. Another thought - I remember somebody saying that log4cpp may disappear. I could merge log4cpp_null (my github project to substitute for log4cpp) into engauge.

**Comment by markummitchell** [comment]
Releases that I build will not have logging. If built with log4cpp then the file will start with a period as '.engauge.log' so it will not clutter the directory.
