### ISSUE TITLE
A point's coordinates information

### ISSUE THREAD

**Issue by j8asic** [markummitchell/engauge-digitizer#249]
Hi,
if I may suggest a couple of non-crucial, but handy, UI features:
- the coordinates of selected point shown in statusbar
- the coordinates table in "Geometry Window" to be editable

Best regards,
Josip

**Comment by markummitchell** [comment]
Thanks for the input. I will look into showing the coordinates of the selected point in the status bar.

The changes to implement editable coordinates in the Geometry Window would be very extensive. I suggest right clicking on the point you want to modify and editing the coordinates in the dialog that appears.

**Comment by j8asic** [comment]
Thank you!
I didn't know about the right-click feature... I agree, it's more appropriate than the Geometry Window idea.
Although, I was trying a double-click for the coordiante modification (CAD program habits), so if you don't have any use for the double click, maybe make it synonymous to the right-click.

**Comment by markummitchell** [comment]
Functionality is already available
