### ISSUE TITLE
Where is the program source file for "segment fill"?

### ISSUE THREAD

**Issue by zhouhaodada** [markummitchell/engauge-digitizer#252]
I want to use this algorithm help to deal with some curve in a picture,if it is not appropriate to ask this question,I feel sorry.

**Comment by zhouhaodada** [comment]
Sorry,this is not appropriate problem.I will find what I need by searching the source file.

**Comment by markummitchell** [comment]
The file src/Segment/SegmentFactory.cpp is a good place to look. The method SegmentFactory::makeSegments has some documentation. Good luck.
