### ISSUE TITLE
Engauge no longer supports PDF documents?

### ISSUE THREAD

**Issue by bmbeyers** [markummitchell/engauge-digitizer#253]
I noticed that somewhere between 9.8 and 10.4, the support for importing a PDF document was dropped. Not sure if this was intentional or not, but was definitely noticed, as this is primarily the type of document that I use in the software.

**Comment by markummitchell** [comment]
Yes that was a tough decision, but I had to drop off support. I was using the popper library which had fallen way out of date. I will try again to see if the situation has improved. Id not, may be there is a new tool I can use instead

**Comment by markummitchell** [comment]
After much work I was able to build the poppler library for windows, with 64 bits. I will incorporate this library.  

If any developers find this comment (via google or similar), poppler required installing cmake build tool and the nasm assembler. Libraries that were built were fontconfig, freetype, iconv, jpeg, png, xml2, openjpeg2, poppler and zlib. Notes describing all the steps are in engauge-digitizer/dev/windows/library_dependencies/README.docx.

**Comment by markummitchell** [comment]
Fixed in release 10.5. I also contacted the poppler team to share the build documentation.

**Comment by bmbeyers** [comment]
Great! Thank you so much!!

**Comment by bmbeyers** [comment]
Not sure if it best to continue along this thread, or start a new one, but I noticed that version 12.1 (for Windows at least) again does not support PDF import.
