### ISSUE TITLE
The data will be sorted by x during picking points.

### ISSUE THREAD

**Issue by VahedCivil** [markummitchell/engauge-digitizer#257]
Hi
In some curve, after increase x value , the curve will be comeback and  the x values will be decrease. In engauge-digitizer during picking point, the data will be sorted order by x. Please add setting to control it by user. 
Thanks for engauge-digitizer.

**Comment by markummitchell** [comment]
Under the menu options Settings, Curve Properties there is the option to set the point connection method to Relation with Straight Lined, or Relation with Smooth Lines. A Relation curve should allow x values that come back.

**Comment by VahedCivil** [comment]
Thank you for replay.
