### ISSUE TITLE
current directory resets every time I export data

### ISSUE THREAD

**Issue by nattydread69** [markummitchell/engauge-digitizer#259]
Hi, 
Every time I export a curve the default path resets to my home folder.
This is really annoying as I want to save all the data sets in the same folder. 
Is this by design?
My OS is ubuntu 18.06 (unity).
Could this be improved?

Thanks from Nat.

**Comment by markummitchell** [comment]
Good point. You are probably correct that it can be improved. I will investigate in the next 24 hours to see if there is any reason why we cannot make the change. My guess is a new release in 48 hours if nothing gets in the way.

**Comment by nattydread69** [comment]
Thanks for your prompt response. This usually just involves saving a string of the last path.

**Comment by markummitchell** [comment]
Right now I am saving one string for Import and Open, and one string for Export and Save. My thinking is that inputs may come from one directory (like Downloads) smd outputs may go to a different directory (like Projects). I can still change this if there is a a more popular approach

**Comment by markummitchell** [comment]
Should be fixed in version 10.7. Thanks for the input

**Comment by nattydread69** [comment]
Thanks Mark :)
