### ISSUE TITLE
Translation files aren't built

### ISSUE THREAD

**Issue by yurivict** [markummitchell/engauge-digitizer#266]
The build doesn't create ```*.qm``` files. Found on FreeBSD.

**Comment by markummitchell** [comment]
Are you building engauge using 'qmake engauge.pro', or trying to run a pre-built release of engauge and that is missing the help files? Any information you can offer can help. If you know how to build the software and are able to make your own file and code suggestions, those will be useful.

**Comment by yurivict** [comment]
I build with 'qmake engauge.pro' within the FreeBSD port. Arch linux seems to have them built, but on FreeBSD they aren't built for some reason.

**Comment by markummitchell** [comment]
In the root directory, try 'lrelease engauge.pro'. That should create the qm files in the translations directory. If you are interested in updating the translations, you can do that at https://www.transifex.com/engauge-digitizer/engauge-digitizer/

**Comment by yurivict** [comment]
This works.
Thanks!
