### ISSUE TITLE
Cannot read engauge-digitizer-10.7.13 files

### ISSUE THREAD

**Issue by Samhaoir** [markummitchell/engauge-digitizer#271]
Dear Sir/Madame,
I have downloaded engauge-digitizer-10.7.13 twice from:
https://github.com/markummitchell/engauge-digitizer/releases
Unfortunately the files are not in a readable format.
I have uploaded a screenshot attached below.
Sorry for the novice approach but I am a newbie at this, can you help me?

Kind regards,

Raymond Henderson
[engauge-digitizer screenshot.docx](https://github.com/markummitchell/engauge-digitizer/files/2159960/engauge-digitizer.screenshot.docx)

**Comment by markummitchell** [comment]
Please ignore source code releases 10.7.X and go back to 10.7

**Comment by Samhaoir** [comment]
Thanks Mark.


Kind regards,


Raymond


________________________________

**Comment by markummitchell** [comment]
Other people are probably having the same problem. I will fix this

**Comment by Samhaoir** [comment]
Hi Mark,


Already using it on Kaplan-Meier curves for clinical trials - it works a treat.


Kind regards,


Raymond Henderson, MSc.,
Doctoral Candidate in Health Economics
Queen's Management School,
Riddel Hall,
185 Stranmillis Road,
Belfast,
Northern Ireland
BT9 5EE
T:00447934684771


________________________________

**Comment by markummitchell** [comment]
If I create a tag then a release is also created, which causes confusion for people trying to download release files. Any tag should be quickly removed using 'git push --delete origin <tag>'. I have just removed all unwanted tags.
