### ISSUE TITLE
feature suggestion: magnetic gridlines

### ISSUE THREAD

**Issue by thorade** [markummitchell/engauge-digitizer#272]
First, thanks for your great tool!
I usually turn on gridlines when digitizing graphs and for getting few "round" values, it would be great to have magnetic gridlines, so that the cursor snaps to values like `0.4` instead of `0.398879`.
Does that sound plausible? And doable?

**Comment by thorade** [comment]
A similar result could probably also be obtained by changing the export a bit for the format "Evenly spaced, in Graph units".
In the picture below, I would like the "x" values to be more round, like only one place after the separator, possibly with the first and last value being less round.

<img width="450" alt="engauge_export_evenly" src="https://user-images.githubusercontent.com/314571/42310408-a761c842-803b-11e8-8b54-8a30b97e1ecd.png">

**Comment by markummitchell** [comment]
The magnetic idea is great. I will add that, while making sure the algorithm works for all cases. A tough case is when the range is very small relative to the range endpoints - like 4.99992 to 4.99993. That kind of range is pretty common. Regarding the fixed number of digits, are you also suggesting zero padding on the right?

**Comment by thorade** [comment]
Thanks for considering that!
I am not so sure what I am suggesting with the fixed number of digits. The idea would be to make the table more readable, and I thought the columns would be more easily visible if e.g. all separators are aligned, or maybe also the decimal separators. This could be done by fixed number of digits, or by whitespace.

**Comment by markummitchell** [comment]
The code already had a "magnetic" implementation that picked nice numbers, but that algorithm did not work well if the dynamic range was very big (e.g. log(xmax)-log(xmin)>>0. I have improved the algorithm and added several tests to check the new code.

Alignment of the data in the Export Settings dialog is not a priority. I think people who want columns to be aligned are (1) reading the exported file into a spreadsheet,(2) using tabs as delimiters and setting the tab width quite large, or (3) copying and pasting from the Geometry Window. I would suggest using View / Geometry Window if you just want to see the data aligned by column. Adding a new setting would require a jump to a new version. If others also request column alignment, this can be added later.

**Comment by markummitchell** [comment]
Forgot to mention the trick of selecting tabs in Export Settinga dialog for quick and dirty column alignment - not perfect but often good enough.
