### ISSUE TITLE
Crash report: selecting two points with the same x value will lead to crash

### ISSUE THREAD

**Issue by k1moradi** [markummitchell/engauge-digitizer#274]
When doing manual digitization, if the user clicks two points having the same x value, the program will crash and all the unsaved work will be lost.

This bug is hard to reproduce but since I have used Engauge extensively in my research I have faced it more than once.

**Comment by markummitchell** [comment]
I will fix this. Thanks for the input.

**Comment by markummitchell** [comment]
I am wondering if you know of a sequence that can trigger this problem, and also what version you were using. I am checking in some upgrades to prevent errors, and what to catch every possible issue.

**Comment by markummitchell** [comment]
I have tried various combinations of the following sequence (1) create 3 axis points in linear/linear graph (2) create zero or more axis points with different x values (3) create 2 curve points with the same x value.

**Comment by markummitchell** [comment]
It turns out that the version 10.8 fix for issue #270 also fixes this issue. I have verified that versions for 10.8 exhibit this problem just as you stated. There were still some changes committed for this issue which should prevent similar problems.

**Comment by k1moradi** [comment]
Thanks! Yes, it seems 10.8 has fixed the issue. I was using 10.7. I will let you know if I found any more bugs. Thanks again!
