### ISSUE TITLE
Installer chmod unexpected

### ISSUE THREAD

**Issue by trevorpe** [markummitchell/engauge-digitizer#275]
I tried using the Debian/Ubuntu installer (`digit-exe-linux-debian-64-bit-installer-10_8.run`) to install Engauge. (This was before realizing there was a package in the normal repositories... My first mistake.)

When the installer asked me for an installation path, I decided to put it in my home directory (`/home/trevor/.engauge_installation`) since I have a separate partition for my home directories and they persist between upgrades of Kubuntu.

The installer was working, and I eventually saw some permission denied errors from `chmod` trying to change the permissions of files well within my home directory documents (there were a few things owned by root). This prompted me to investigate, because I thought that there should be no way of the installer messing with files outside of the installation directory (or at least that's what I expected).

The permissions of my entire home directory were affected. I suspect somewhere in the installation scripts, `chmod` was used recursively and probably followed some symlink somewhere to eventually end up in my home directory (the parent of the installation directory). I opened the file with `vim`, but there are only a couple of `chmod` commands there, neither of which was recursive. I didn't look any further.

Luckily, I had just made a backup of my home partition less than a week ago and was able to use that and a quick script to change most of my permissions back to what they were. I just thought I'd create the issue here in case there is unintended behaviour in the installer (or if you should plaster "DON'T INSTALL TO HOME DIRECTORY" somewhere).

**Comment by markummitchell** [comment]
Thanks for the feedback. I can replicate the problem, and need to fix this right away.

**Comment by markummitchell** [comment]
Fixed in release 10.9
