### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [markummitchell/engauge-digitizer#276]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CmdPointChangeBase::saveDocumentState](https://github.com/markummitchell/engauge-digitizer/blob/7321597d0b64ec685b021d0d3322de6de3a020a4/src/Cmd/CmdPointChangeBase.cpp#L41 "CmdPointChangeBase::saveDocumentState function")
- [LoadImageFromUrl::deallocate](https://github.com/markummitchell/engauge-digitizer/blob/7321597d0b64ec685b021d0d3322de6de3a020a4/src/Load/LoadImageFromUrl.cpp#L30 "LoadImageFromUrl::deallocate function")
- [Pdf::load](https://github.com/markummitchell/engauge-digitizer/blob/7321597d0b64ec685b021d0d3322de6de3a020a4/src/Pdf/Pdf.cpp#L56 "Pdf::load function")

**Comment by markummitchell** [comment]
Before making these changes, I would like to understand your goal(s) for these changes

**Comment by elfring** [comment]
I hope that it can be achieved to avoid mentioned questionable source code somehow.
* Deletion of unnecessary checks
* I imagine that the usage of smart pointers can help also in this case.

**Comment by markummitchell** [comment]
Implemented.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/markummitchell/engauge-digitizer/commit/6384228624d35f35abe1cb74017e647304ba3806 "Remove zero guard on deletes").

A few update candidates were left over.
Examples:
* [DlgSettingsGeneral::load](https://github.com/markummitchell/engauge-digitizer/blob/7195d840b749755a9afb1741ff8f5817b6f78127/src/Dlg/DlgSettingsGeneral.cpp#L117)
* [GridLines::clear](https://github.com/markummitchell/engauge-digitizer/blob/7321597d0b64ec685b021d0d3322de6de3a020a4/src/Grid/GridLines.cpp#L19)

**Comment by markummitchell** [comment]
Thanks. I think I have them all now.

**Comment by elfring** [comment]
Thanks for [another source code improvement](https://github.com/markummitchell/engauge-digitizer/commit/6241ac23dbed60ccbf4fd8a2b874da7da6a66ea7 "More zero guard cleanup").
