### ISSUE TITLE
Difficult image for segment fill

### ISSUE THREAD

**Issue by andrewk8** [markummitchell/engauge-digitizer#284]
Using Version 10.9.
I have a high quality image that's proving very difficult to clean up for automatic segment recognition or manual segment fill.  The curves are quite simple, but it's a black and white image with many gridlines.  Automatic gridline removal doesn't work on this image. Manual gridline removal takes many minutes to complete and slices up the curve segments extensively.

Source file was black and white vector format.  I opened in GIMP @ 300 dpi to convert to raster.  Converted RGB to grayscale.  No improvement in Engauge outcome further converting to black and white bitmap.

Submitting this image to get suggestions for cleaning up.  Also can use for test cases for future versions.

![military handbook 5h](https://user-images.githubusercontent.com/16465258/45177020-bce8d900-b1df-11e8-8f5c-bdd5784d04e0.png)

**Comment by markummitchell** [comment]
I will see what can be done to speed this up (it is running quite slowly) and make the grid lines go away more effectively.

**Comment by markummitchell** [comment]
Pre-releases are now at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/build/job/n9ctnva6tjw05ire/artifacts (64 bits) and https://ci.appveyor.com/project/markummitchell/engauge-digitizer/build/job/nxyob04bu3dms3k0/artifacts (32 bits)

**Comment by andrewk8** [comment]
Pre-release working much better.  Thanks.
