### ISSUE TITLE
Curve Fitting Window Broken (10.9)

### ISSUE THREAD

**Issue by btrust** [markummitchell/engauge-digitizer#287]
OS:
Fedora 4.19.0-0.rc2.git3.1.fc30.x86_64 & macOS High Sierra 10.13.6
Engauge Version 10.9

Version 10.9 has broken the curve fitting window.  It only calculates polynomials to the x^1 degree even though the capability to curve fit to the 9th degree should be available.  I discovered this when reviewing old .dig file curves that were generated in 10.4 and noticed they were different in 10.9.

Good news - the issue is resolved when downgrading to 10.4.  I've demo'd this on linux and macOS as well as numerous *.dig files and new files from scratch.

Please let me know if you need anymore details.  Btw, AWESOME project - I literally couldn't do my job without it! Thank you!

**Comment by markummitchell** [comment]
Windows prerelease versions with fixes for this are at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master. Click on either 32 or 64 bit versions, then the Artifacts link, then download the 7z file and decompress it.

**Comment by markummitchell** [comment]
Some checks for overflow needed to be a bit smarter. Seems to be working now. Thanks for the input!
