### ISSUE TITLE
Suggestion: How about figures with x or y axis in log scale

### ISSUE THREAD

**Issue by Clear-up** [markummitchell/engauge-digitizer#289]
Hi,
I really like the tool, but in my field, most figures are in /logx or /logy like the figure below. Would you consider add the function to export coordinates of a figure with log-scaled x or y axis?

Attached is a figure with logx (base 2)
![figure](https://user-images.githubusercontent.com/18334656/46756119-b644fa00-cc94-11e8-89e1-5ef30b4b51b2.png)

**Comment by markummitchell** [comment]
If I remember correctly (I am not near a computer), you can use Settings/Coordinates to get log coordinates

**Comment by markummitchell** [comment]
I think we are good on this one.
