### ISSUE TITLE
Need help with source code: capture points while mouse is pressed.

### ISSUE THREAD

**Issue by raullaasner** [markummitchell/engauge-digitizer#293]
I would like the points to be captured as I'm dragging the mouse while the left button is pressed. This way I don't have to be constantly clicking as I'm moving along the curve.

I have modified the following section of `DigitizeStateCurve.cpp`:

```C++
void DigitizeStateCurve::handleMouseMove (CmdMediator * cmdMediator,
                                          QPointF posScreen)
{
    //  LOG4CPP_DEBUG_S ((*mainCat)) << "DigitizeStateCurve::handleMouseMove";
    if (mousePressed) {
        // OrdinalGenerator ordinalGenerator;
        // Document &document = cmdMediator->document ();
        // const Transformation &transformation = context ().mainWindow ().transformation();
        // QUndoCommand *cmd =
        //     new CmdAddPointGraph (context ().mainWindow(),
        //                           document,
        //                           context ().mainWindow().selectedGraphCurve(),
        //                           posScreen,
        //                           ordinalGenerator.generateCurvePointOrdinal(document,
        //                                                                      transformation,
        //                                                                      posScreen,
        //                                                                      activeCurve ()));
        // context().appendNewCmd(cmdMediator,
        //                        cmd);
        std::cout << "coordinates: "<< posScreen.x() << "," << posScreen.y() << "\n";
    }
}

void DigitizeStateCurve::handleMousePress (CmdMediator * /* cmdMediator */,
                                           QPointF /* posScreen */)
{
    LOG4CPP_INFO_S ((*mainCat)) << "DigitizeStateCurve::handleMousePress";
    mousePressed = true;
}

void DigitizeStateCurve::handleMouseRelease (CmdMediator *cmdMediator,
                                             QPointF posScreen)
{
  LOG4CPP_INFO_S ((*mainCat)) << "DigitizeStateCurve::handleMouseRelease";

  // Create command to add point
  OrdinalGenerator ordinalGenerator;
  Document &document = cmdMediator->document ();
  const Transformation &transformation = context ().mainWindow ().transformation();
  QUndoCommand *cmd = new CmdAddPointGraph (context ().mainWindow(),
                                            document,
                                            context ().mainWindow().selectedGraphCurve(),
                                            posScreen,
                                            ordinalGenerator.generateCurvePointOrdinal(document,
                                                                                       transformation,
                                                                                       posScreen,
                                                                                       activeCurve ()));
  context().appendNewCmd(cmdMediator,
                         cmd);
  mousePressed = false;
}
```

Currently, when the left button is pressed (`mousePressed` is enabled and disabled in `handleMousePress` and `handleMouseRelease`), all it does is print the coordinates to the screen. Instead, I would like it to capture the coordinates as points added to the current curve. Is this possible without too much work? You can see my naive attempt at this above (I've commented it out because it didn't work). I had copied the lines from `handleMouseRelease` hoping it would have the desired effect.

If someone familiar with the code would even point me at the right direction I would be grateful. The ability to quickly capture points this way would save me a lot of time with some plots I have to work with.

**Comment by markummitchell** [comment]
Those could be good improvements. I will explore them and get back to
you.There may be a version 11 release soon and thiscould be added

**Comment by markummitchell** [comment]
The Segment Fill mode might be useful, since one click automatically places multiple points along a curve segment.You may need to play with the Color Filter settings to make this work well.

Your curves seem very straight. I am thinking the straight parts would need very few points added to capture them accurately. I can look at your dig file.

**Comment by raullaasner** [comment]
I tried segment fill but it is not able to capture these curves. It seems to me that it only works with solid lines (not symbols or dotted lines for example).

What is a dig file?

**Comment by raullaasner** [comment]
I pushed the changes to my own [copy](https://github.com/raullaasner/engauge-digitizer) so you can see exactly what I meant if you are interested.

For testing, import some image, click on "Curve Point Tool", click and hold down somewhere on the image and start dragging the mouse. Do this for different "rapid capture levels" with can be set by the + and - buttons on the toolbar, like this:
![demo](https://user-images.githubusercontent.com/13432886/47036974-ba1cc480-d14b-11e8-9ac1-7882e249afcb.jpeg)

Again, this is just a hack and could probably be made better if there is wider interest. For now, this works flawlessly for my personal use.

**Comment by raullaasner** [comment]
Here is the dig file: [test.dig.zip](https://github.com/markummitchell/engauge-digitizer/files/2484476/test.dig.zip)
Point Match mode works sometimes for me for not on this plot.

**Comment by markummitchell** [comment]
Yes, Point Match does not work well. Since I was able to get good results using the exiting approaches, and I am trying to keep the user interface as simple as possible, I will postpone adding this new digitizing strategy for now. Thanks for the input.
