### ISSUE TITLE
log4cpp/Category.hh: No such file or directory

### ISSUE THREAD

**Issue by OnlyCjay** [markummitchell/engauge-digitizer#295]
After executed following steps，I encountered  compiler error: 
"log4cpp/Category.hh: No such file or directory"

1. Download from master branch

2. Open engauge.pro with qt5.11 on Windows

3. Build

**Comment by markummitchell** [comment]
Try adding CONFIG+=log4cpp_null to your qmake line. That will build with the bundled version of log4cpp

**Comment by markummitchell** [comment]
In Windows, OSX and Linux a much harder solution is to download log4cpp and build it, and then set environment variable LOG4CPP_HOME to point to the built directory.

In OSX and Linux you can install log4cpp using the package manager, and then set LOG4CPP_HOME.
