### ISSUE TITLE
Feature suggestion: easier determination of axes

### ISSUE THREAD

**Issue by raullaasner** [markummitchell/engauge-digitizer#306]
I implemented a small feature for determining the axis points when the tics are not exactly at the endpoints of axes. In this example,
![example0](https://user-images.githubusercontent.com/13432886/52007093-c844e580-249b-11e9-80e0-27d7f8528c0d.png)
the user would first click on the tic at "1" to determine the x-coordinate, and then on the tic at "-10" to determine the y-coordinate. A point then appears where the two tics would intersect, allowing the user to enter -10 and 1 as the axis point coordinates in the dialog window.

I've found this tremendously useful for personal use (see the code [here](https://github.com/raullaasner/engauge-digitizer/tree/personal)) and perhaps there is also wider interest. Previously, I had to move the mouse to a number on the x-axis, remember the pixel coordinate, then move to a number on the y-axis, remember the coordinate, and then move to where the tics would intersect. However, this was inconvenient and quite a bit slower.

Feel free to close this issue as I only meant it as a comment.

**Comment by markummitchell** [comment]
That is clever. There is an alternate solution which is to do Import Advanced and select 4 axis points. Then 2 points are put on the x axis without any y value, and 2 points are put on the y axis without any x value. I am thinking a suggestion can be put into the axis point edit dialog since it is not well known. An advantage of that approach is it handles rotation and shearing distortions automatically.

**Comment by raullaasner** [comment]
Oh, so that is what the 4 axis point option does! Good to know. Well, it took me about half a day implementing this so at least it was good exercise. :)

**Comment by raullaasner** [comment]
Actually, I've seen some corner cases where I think my method could be better. Consider this plot (I've deleted most data points):
![example](https://user-images.githubusercontent.com/13432886/52087700-28a95500-2578-11e9-9d80-3bcbfcc57e21.png)
You can't select (0,4.30) as an axis point because it's hidden behind the data point. The best you can do is select (0,4.28) but this makes it a little less accurate (I've seen plots where this results in greater loss of accuracy). The 4-point method also wouldn't help here. With my method, I can first click anywhere on the y-axis and then on the part of the 4.30 tic that is visible behind the data point. The axis point is then generated exactly at the location (0,4.30).

Just thought it's worth mentioning (I've digitized a few thousand figures with this tool thus far and such corner cases do come up).
