### ISSUE TITLE
Export interpolation range starts from Graph Unit zero instead of axis value.

### ISSUE THREAD

**Issue by ccampb19** [markummitchell/engauge-digitizer#308]
Version: 10.11

To reproduce:
-Import this image and set the axes {(300,0),(1100,0),(300,0.7)}
-Use the segment tool and curve point tool to select the curve.
-Settings > Export Format > Interpolate Ys at evenly spaced X values
-Choose an interval of 10 Graph Units
-Observe preview and the exported file interpolate starting at x=0 instead of from some point on the graph.

![bug](https://user-images.githubusercontent.com/43229278/52965055-e94d7780-3371-11e9-94af-905adb1aebc4.png)

**Comment by markummitchell** [comment]
I have started working on this.

**Comment by markummitchell** [comment]
Definitely a good improvement.

**Comment by ccampb19** [comment]
Great! Thank you for developing this program.
