### ISSUE TITLE
logarithmic y-axis is incorrect in export preview

### ISSUE THREAD

**Issue by ccampb19** [markummitchell/engauge-digitizer#309]
Version: 10.11

To reproduce:
-Import the lower image and select axis points {(200,1e4),(1000,1e4),(200,1e8)} and a curve. Particularly, select some points on a curve near the left end of the x axis.
-Settings > Coordinates
-Set y scale to "log"
-Settings > Export format
-Observe y values in preview. For instance, my first two points in the image below should be less than 10,000, but they are 17k and 87k. Further, "interpolate Ys at evenly spaced X values" is unhelpful.
-Interestingly, the values appear to be correct when exported.

![image](https://user-images.githubusercontent.com/43229278/52966401-31ba6480-3375-11e9-98bb-c7cd49846194.png)

![bug2](https://user-images.githubusercontent.com/43229278/52966111-75f93500-3374-11e9-8ac5-bc6ec132d0bd.jpg)

**Comment by markummitchell** [comment]
Thanks for the input, and the clear explanation. I will look into this right away.

**Comment by markummitchell** [comment]
Thanks for the great input!
