### ISSUE TITLE
Cannot save .dig file or export .csv file

### ISSUE THREAD

**Issue by sphh** [markummitchell/engauge-digitizer#310]
Whenever I try to save the .dig file or export to a .csv file, I get the following error after selecting `~/Downloads/data.dig` or `~/Downloads/data.csv`:
```
Cannot write file /run/user/1000/doc/17713/data.dig: Function not implemented
```
or
```
Unable to export to file /run/user/1000/doc/14455743/data.csv
```

My installation:
Linux Mint 19.1
Flatpak 1.0.7
Engauge Digitizer 10.11 (installed as flatpak with Software Manager)

I started Engauge Digitizer with
```
flatpak run io.github.markummitchell.Engauge_Digitizer
```
or from the menu (same result).
The command line does not show any error at all.

Is there a way around to enable saving .dig and exporting to .csv files? Thank you for your help!!

**Comment by markummitchell** [comment]
My guess is the security sandbox probably is not letting you write to the Downloads directory, since that could let an app write a virus installer to that directory that the user might run later. Can you try other directories?

**Comment by sphh** [comment]
I tried to save it into my home directory `~` and it works. Not an ideal solution, but I can live with it.

Thanks for your help.
