### ISSUE TITLE
Export at grid lines

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#315]
Need a new export strategy in which curve values are interpolated at grid line X values (the vertical grid lines). This will give the user control over where the interpolations will happen, and is needed since the current 'regularly spaced points' option is automated and offers no user control. The first implementation (which works but is not released) adds that option, but before official release a new feature must be added to let the user determine how endpoints are handled. Should raw values at endpoints not on grid lines be used? Should they just be dropped? Should extrapolation be used?

**Comment by oopman2002** [comment]
What I do on the curves I digitize is to use a VBA linear interpolation routine to create uniform data steps and then interpolate from the digitized data to a normalized set of data. It takes a couple of extra steps but works pretty good for pump curves.
