### ISSUE TITLE
software crash when using point match tool

### ISSUE THREAD

**Issue by ucasbusiniao** [markummitchell/engauge-digitizer#317]
I just updated to the latest version today, the software crashed every time just when I switch to point match tool after I finished defining xy coordinate. Can anyone help with this? Thanks in advance. The alert is as below,
Crashed Thread: 0 Dispatch queue: com.apple.main-thread

**Comment by markummitchell** [comment]
Hi, I will unvestigate today, Mark

**Comment by ucasbusiniao** [comment]
Hi Mark,

Thanks so much.

Best,
Liyuan

**Comment by markummitchell** [comment]
Thanks for the input. I have implemented a fix and will release a new version as soon as #319 is completed, which should be very soon. A Windows pre-release is available at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/083c6ptrug17ft2c/artifacts. You will need a tool like Winzip to unpack the file.

**Comment by ucasbusiniao** [comment]
Hi Mark,

Thanks for your efforts, my laptop is Mac, hope the right version will soon be available. Thanks again.


Best,
Liyuan

**Comment by markummitchell** [comment]
The release with this fix will be today.

**Comment by markummitchell** [comment]
Released as version 11.1

**Comment by ucasbusiniao** [comment]
Happy to know that, thanks so much, Mark. 

Best,
Liyuan
