### ISSUE TITLE
Exporting digitized figures with multiple traces appends irrelevant data at the head or tail of the trace.

### ISSUE THREAD

**Issue by k1moradi** [markummitchell/engauge-digitizer#318]
I am digitizing the following image.

![image](https://user-images.githubusercontent.com/18602635/56526167-f88ba580-6519-11e9-9cf8-4e7eec774b6e.png)

When I export and plot I get the following plot.

![image](https://user-images.githubusercontent.com/18602635/56526401-38528d00-651a-11e9-9fd7-296688668371.png)

Also, it is great that program exports both traces at once but I wished I had the option of choosing which trace needs exporting.

**Comment by markummitchell** [comment]
Hi, I tried your file using the same coordinates, and believe the code is working as expected. This case, which I call the "side by side" case, is pretty rare.

Most people have curves that stretch from about the same minimum X value to about the same maximum X value. For these curves, it is safe to extrapolate a little outside of each curve's actual bounds. In fact, the default behavior for several years has been to extrapolate so if one curve starts at, say, 5.0 and the other starts at 5.001, they can get values at 5.0 for both curves. 

Where extrapolation gets into trouble is when the curves do not start and end together. In your case, we have "side by side" curves with the first curve defined from -430 to -250, and the second curve defined from -180 to -15. Extrapolation of the first curve over to the second curve gives the long straight line you have in your sample image. Sometime people want this to happen, but in your case this behavior is probably not useful and also is confusing.

I recommend you try unchecking the Extrapolation button in the Export Settings. Also, you can drag curve names back and forth to select/deselect them for export (this addresses your question about choosing which trace gets exported).

Thanks for the great input. It really helped for me to figure out what was happening.

I will leave this issue open until it is known for sure that export is working.

**Comment by markummitchell** [comment]
Also, if you start with Import Advanced you can have 2 sets of axes - one per curve.

**Comment by k1moradi** [comment]
Thanks Mark for fixing the bug!
