### ISSUE TITLE
Is "save as default" button on the export format menu working?

### ISSUE THREAD

**Issue by k1moradi** [markummitchell/engauge-digitizer#324]
I want to globally set the export format settings but it seems "save as default" button is not able to do this.

**Comment by markummitchell** [comment]
I just tested in Linux and it seems to be working as designed with one minor problem that I am turning into a bug issue. 

'Save as Default' means the settings will reappear in newly imported documents that are created afterwards. Documents that were created before 'Save as Default' was pressed will continue to use their current export settings.

The one problem, in terms of not operating as designed, is that the 'Override CSV/TSV' control is not getting saved. I will fix this.

If you want saved export settings to appear in all documents that are opened later, then I would suggest a new 'Use default' button to pull in the default settings.

**Comment by markummitchell** [comment]
In Linux you can see the settings at $HOME/.config/Engauge/Digitizer.conf

**Comment by k1moradi** [comment]
Thanks a lot! "Use default" button will be very helpful. I have to vet digitization and finally export 800 dig files. Having a global override option for the export format will help me a lot since dig files are already created and unfortunately, all of them have saved with an unwanted default export setting. I am going to use the same settings to export them all. At this point, I need to set the export format for each file before export, which is doable but error-prone.

Another way to improve export is to show some of the options on the export file dialog. However, I am not sure Qt has such an option or not.

Could you please let me know the conf file location in windows?
