### ISSUE TITLE
Add Load Default button to Export dialog

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#326]
Add Load Default button in the dialog for editing Export setttings.

This issue was suggested in #324

**Comment by markummitchell** [comment]
@https://github.com/k1moradi You can try out a pre-release by downloading from https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/a6tx4db6ybyujxm9/artifacts. Use 7zip to open up the file.

**Comment by k1moradi** [comment]
I checked the pre-release binary. In the export setting menu, I see the load default button, when I press it **my** default settings get loaded, but after pressing of and exporting the CSV file has not the format I set in the export menu. When I open the export settings menu, I see the original settings, not my defaults.

Before pressing the Load defaults:
![image](https://user-images.githubusercontent.com/18602635/57947656-7c347a00-78ad-11e9-82ed-57fae8889f17.png)

After pressing the load defaults
![image](https://user-images.githubusercontent.com/18602635/57947694-95d5c180-78ad-11e9-847a-0e1ffba5b217.png)

I pressed OK and reopened the export format menu
![image](https://user-images.githubusercontent.com/18602635/57947740-b6058080-78ad-11e9-8b3a-7ee681311b9e.png)

You can see the OK button did not do what it should do.

----------------------------------------------------------------------

PS: While you are working on this menu, from the shape of the screenshots you can see that the width and height of the settings menu are smaller than what they should be.

After adjusting the width on my computer.
![image](https://user-images.githubusercontent.com/18602635/57947991-768b6400-78ae-11e9-91f1-b8b0fc3300b1.png)

I think this might be related to the display DPI on my computer. The following figure:
![image](https://user-images.githubusercontent.com/18602635/57948070-ad617a00-78ae-11e9-8389-c207a1f15e11.png)

I checked with an old secondary display and this height and width problem was not there.
![image](https://user-images.githubusercontent.com/18602635/57948227-0f21e400-78af-11e9-8866-99c8a4235f8b.png)

**Comment by markummitchell** [comment]
The Default button can be tested in Windows 64 bit by downloading and extracting https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/y3ow8xpl52wx33qh/artifacts.

**Comment by k1moradi** [comment]
Thanks a lot! You are awesome! The "load default" button works now. 
(I did not find your binary so I compiled the code myself. :))
