### ISSUE TITLE
Incompatible Encoding on Old Engauge Files

### ISSUE THREAD

**Issue by kylesower** [markummitchell/engauge-digitizer#327]
Using your DumpGraphAndScreenCoordinates.py script, I discovered that old Engauge files have a strange encoding that prevents them from being read correctly. I've attached an example file (though you'll have to change the file extension from .txt to .dig). Sometimes it is possible to open the file in a newer version of Engauge and overwrite the save, which resolves the encoding issue. However, it would be nice to have a faster conversion that is scriptable for a large number of files.

[1952_bro_zem-134 Fig_2_superconducting_(magnetic_field_off).txt](https://github.com/markummitchell/engauge-digitizer/files/3188812/1952_bro_zem-134.Fig_2_superconducting_.magnetic_field_off.txt)

**Comment by markummitchell** [comment]
The old format was binary. You are right - the scripts should be upgraded to work with that old format. I will modify the file reading code to support the old format. It should take about a week. Would that time frame work for you?

**Comment by markummitchell** [comment]
Should be working now.

**Comment by kylesower** [comment]
Just tested it - works great. I just had to change the directory in the upgrade function to point to the new Engauge install. Thank you!

**Comment by markummitchell** [comment]
The script now offers some help for setting the path.
