### ISSUE TITLE
Support drag and drop of PNG file

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#331]
PNG file dragged into Engauge should be imported.

**Comment by markummitchell** [comment]
@k1moradi What release and platform are you using? I have tested on various systems and did not see the problem. If in linux, can you try installing a package like libpng?

**Comment by k1moradi** [comment]
I reproduced this bug on windows 10 64 bits. I tested 11.2 without installer and also 11.3 version that I compiled myself.

Just drag a PNG file

![image](https://user-images.githubusercontent.com/18602635/58810016-0d645a00-85eb-11e9-8609-7fd17bbb8f91.png)

Nothing happens if you drop it.

**Comment by markummitchell** [comment]
Can you try the prerelease?

**Comment by k1moradi** [comment]
It works now! Thanks a lot.

PS: Theming is different when I compile from source on windows.
For example, the cascade menu on left (my build) is white, but the right one (your prerelease) is grey.
![image](https://user-images.githubusercontent.com/18602635/58827612-7959b900-8611-11e9-8e32-59b05f760545.png)

![image](https://user-images.githubusercontent.com/18602635/58827762-cdfd3400-8611-11e9-9ac0-1f7005220475.png)

**Comment by markummitchell** [comment]
Great

The theme issue could be from the different themes (see #336), or just different build systems.
