### ISSUE TITLE
Any suggestions on digitizing this figure?

### ISSUE THREAD

**Issue by lonelykid** [markummitchell/engauge-digitizer#343]
Any suggestions will be appreciated.
![image](https://user-images.githubusercontent.com/2936633/61090515-f7795e80-a40c-11e9-933b-132779364720.png)

**Comment by markummitchell** [comment]
Under Settings/CurveList you can add add new curves. Then under Settings/CurvePropertias you can change the curve types from Functions to Relations. Then digitize each curve separately, picking the curve name in the toolbar. At some point you will need to add 3 axis points. Relations curves can have multiple y values for any x value.

**Comment by lonelykid** [comment]
Thank you! Is there a way to correct the order of points? You can see they are connected in a wrong way.
![image](https://user-images.githubusercontent.com/2936633/61137878-59c97200-a494-11e9-94b5-52d0c4b260f3.png)

**Comment by markummitchell** [comment]
New points need to be added close to the existing points to continue the line.
