### ISSUE TITLE
data export with x- and y-axis as log scale

### ISSUE THREAD

**Issue by celentanos** [markummitchell/engauge-digitizer#345]
When I set x- and y-axis as log scale and try export data the program hangs. It seams to be an endless while loop in `ExportValuesXOrY ExportXThetaValuesMergedFunctions::periodicLogGraph(...)`
function.

**Comment by markummitchell** [comment]
Hello, I am wondering if you have a sample data file that triggers the problem. Sorry for the slow response

**Comment by celentanos** [comment]
https://yadi.sk/d/MPqkjXODey32gw this is the corresponding file.

I only made the changes in Coordinates- and in Export Format Settings (see figures below). Then I tried to export the data in csv format. But the program starts to hang (with 100% CPU load in an one thread) when the two axes are set to log and you click on the export settings. 

![Screenshot_20190725_132921](https://user-images.githubusercontent.com/1735475/61871379-f4886e80-aee0-11e9-82d4-4d9649fa04c6.png)
![Screenshot_20190725_132956](https://user-images.githubusercontent.com/1735475/61871378-f4886e80-aee0-11e9-9eec-7563c0506886.png)

**Comment by markummitchell** [comment]
Thanks. I am able to see the problem. This should be fixed quickly. After testing you can try out the fixed version - about 2 days.

**Comment by markummitchell** [comment]
There is a 64 bit Windows pre-release at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/tahk5voottucfy38/artifacts. You can extract that file using tools like 7zip or winzip.

**Comment by celentanos** [comment]
The program has no hangs more, but the values are not sampled at the specified intervals (see figure below). I have the interval from 0.25 to 2.0 (see figure below).
![Screenshot_20190729_122539](https://user-images.githubusercontent.com/1735475/62041991-455bd800-b1fd-11e9-8f5a-5c142d40f4b3.jpg)

![Screenshot_20190729_123449](https://user-images.githubusercontent.com/1735475/62042025-53a9f400-b1fd-11e9-98e0-b11b95c15228.png)

**Comment by markummitchell** [comment]
That is working as designed. The step factor in a log plot is multiplicative. So values greater than 1 are needed since the pattern is ymin, ymin*scale, ymin*scale^2, ..., ymax

The Export Settings dialog now disables the Ok button, and does not insert a series of points, when the step is less than one for log scale.

**Comment by celentanos** [comment]
Good, I did not know that. The program works as you described. So I will mark this issue as solved. Many thanks :)

**Comment by markummitchell** [comment]
Thanks for the input. This fix will help many people in the future
