### ISSUE TITLE
Possible to add upright triangles to data point shapes?

### ISSUE THREAD

**Issue by kylesower** [markummitchell/engauge-digitizer#346]
Currently, Engauge only has triangles that point down, but it would be nice to also have triangles that point up.

**Comment by markummitchell** [comment]
Yes. I will do this

**Comment by kylesower** [comment]
Awesome, thank you!

**Comment by markummitchell** [comment]
A Windows 64 bit pre-release is at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/7p8j39b6hvf1s5o9/artifacts. The new point types are Hourglass and Triangle2.

**Comment by kylesower** [comment]
Great, thank you.
