### ISSUE TITLE
New engauge build can't read files that are saved with new engauge build

### ISSUE THREAD

**Issue by kylesower** [markummitchell/engauge-digitizer#347]
Engauge 12.0, when opening a file that was saved with Engauge 12.0, gives (roughly) the error "Cannot read file "PATH to .dig" from directory "PATH to png"". The second path is a bit different if you pasted the image in rather than importing. I found that changing the version number in the new dig file from 12.0 to 11.3 allows Engauge to open the file.

**Comment by kylesower** [comment]
Is there any way you could rebuild it with the bug fix? Thank you.

**Comment by markummitchell** [comment]
Currently there is a build at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/x6wuxsys3yo8ih2f/artifacts. When there is a new commit, that file at that URL disappears. In general, you can get the most recent pre-release build by:
* Click on the bottom green button at https://github.com/markummitchell/engauge-digitizer
* Click on the bottom line that says 'BUILD_TYPE=x64'
* Click on 'Artifacts' on the right
* Download the 7z file

**Comment by markummitchell** [comment]
Seems to be working
