### ISSUE TITLE
French translation, version 11.3

### ISSUE THREAD

**Issue by Netphilou31** [markummitchell/engauge-digitizer#348]
Hi,
After installing version 11.3, I noticed that the French translation of menu items and some other texts contains a lot of problem related to the ' character. Indeed, the words contains the ' character and the apos; word. example: "File" menu ("Fichier" in French), item "Import (Image Replace)...", the french translation is "Importer (Remplacer l'apos;image)..." whereas it should be "Importer (Remplacer l'image)...". I did see only problems related to the quote character but mostly everywhere in the software.
Best regards,
Phil.

**Comment by markummitchell** [comment]
I think if you unzip the attached file into the directory currently containing the engauge_fr.qm, you can try out the new translations. Thanks for the input.

[engauge_fr.qm.zip](https://github.com/markummitchell/engauge-digitizer/files/3508306/engauge_fr.qm.zip)

**Comment by Netphilou31** [comment]
Hi,

Thanks for the fixed translation file, it seems to be Ok now (I didn't
browse all the places but the ones I tried are displaying correctly).

Best regards,

Phil

Le ven. 16 août 2019 à 08:29, Mark Mitchell <notifications@github.com> a
écrit :
