### ISSUE TITLE
crash on csv version 10.12

### ISSUE THREAD

**Issue by captain-facepalm** [markummitchell/engauge-digitizer#349]
First of all: It's a great tool!

The software crashes when I try to expert the data. Maybe it is because I did fill the first graph with any points. Because it did expert correctly when I just added a handful of points.

The error report is attached. Zipped because GitHub does not like XML files apparently.

Cheers

P.S.: OpenSuse Leap 15.1 64bit, engauge version 10.12 install from suse repo.

[error_report.zip](https://github.com/markummitchell/engauge-digitizer/files/3512098/error_report.zip)

**Comment by markummitchell** [comment]
This issue was fixed for #345. You should be good to go with the newest release. Can you upgrade?

**Comment by markummitchell** [comment]
Released in version 12
