### ISSUE TITLE
Help -> Tutorial -> Next Button -> Crash

### ISSUE THREAD

**Issue by jkulesza** [markummitchell/engauge-digitizer#353]
Engauge Digitizer Version 12.0, installed from 12.0 Github Release PKG
macOS 10.14.6

Going to the Help menu, Tutorial entry, and then clicking next causes a crash on two of my macOS-based machines.

**Comment by markummitchell** [comment]
I made a fix that you can try in digit-exe-osx-12.1-prerelease.pkg which is available in the 12.0 release.

**Comment by jkulesza** [comment]
That fixed, thanks!

**Comment by markummitchell** [comment]
Great!
