### ISSUE TITLE
Automation of extracting point series from images

### ISSUE THREAD

**Issue by zhongjingjogy** [markummitchell/engauge-digitizer#354]
Hello,

I am working on a project which is in need of collecting data from publication. Generally, the data provided is presented as image, and I used to collect them with GetData or engauge-digitizer manually, which is demonstrated as follow
![2019-6a](https://user-images.githubusercontent.com/9261231/64907969-58ceee00-d72c-11e9-8f76-b359032b8665.PNG)

Unfortunately, I have plentty of data like this, over 200 images, which takes too much time for digitizing. In the image above, the dots are important and I have to extract them by series according to the colors and markers. 

I would like to ask for some advanced suggestions for doing this work less painfull.

Thanks and best regards.

Jing

**Comment by zhongjingjogy** [comment]
Here might be a possible solution,

1. Generate the .dig files for every image with a Python script
1.1 Setup the labels for all the lines
1.2 Setup a default coordinate for every .dig file
2. Manually change the coordinates for every .dig file with Engauge-Digitizer
3. Manuually collect the points with Engauge-Digitizer
4. Export the points with Engauge-Digitizer

I am following this solution and I would like to figure out whether it is time-saving.

**Comment by zhongjingjogy** [comment]
I might need some suggestion on converting .PNG to the cdata,
```
<![CDATA[/*encoded-png-data*/]]>
```

Is it .PNG->base64? I try this one. But the encoded string is not the same as that encoded by Engauge-Digitizer.

**Comment by markummitchell** [comment]
This seems like a tough problem. Maybe this can help:

1. 1. In the contrib/python directory there is the ParseDig python class for reading dig files. An example usage is in ExampleParseDig.py. This approach takes care of handling the PNG encoding/decoding
2. File / Import (Image Replace) is used by some people in similar situations. Although this does is run manually and not automated, you may not want this solution, which was developed well before the python code.

**Comment by zhongjingjogy** [comment]
Thanks for the suggestions! I had tried to go over the repository and I didn't manage to do that yet. Maybe the documentation should provide more details on manipulating the project file and the Python utilities. 

Currently, I have done everything manually. The interpolation in this project is awesome and it saves me a lot of time aligning the axes on my own.

Best regards
