### ISSUE TITLE
cannot read file for the original directory

### ISSUE THREAD

**Issue by KRai2007** [markummitchell/engauge-digitizer#363]
Hi. It's my first time to use ENGAUGE.
But I got stuck in the very beginning.
![problem](https://user-images.githubusercontent.com/50482040/71143623-9a58c300-225e-11ea-973c-48c7ac06e1e5.png)
It says cannot read file from the original directory.
I will be grateful if you could show me how to fix this.
Thank you.

Sincerely,
Yao

**Comment by markummitchell** [comment]
Hello,
Use File/Import to import a simple image. If you have multiple graphs in the same image then use File/Import(Advanced). Once you import an image, some help will be offered. 
Good luck

**Comment by KRai2007** [comment]
Thank you for your reply.
Actually it was strange cuz I successfully imported my wallpaper and another photo.
Does ENGAUGE has some restraints on file size?
The failed jpg is 25kb, and successful 2 pictures are over 100kb.

**Comment by markummitchell** [comment]
The file may be corrupt or use an unsupported format, although I have not heard of problems with unsupported formats. If the file is not private, you can try copying it to this forum and I can look at it.

**Comment by KRai2007** [comment]
![sim](https://user-images.githubusercontent.com/50482040/71148509-31c61200-226f-11ea-8b52-a90ed873db3e.jpg)
I downloaded it from a published paper in 2013, jpg file.
I can open it with windows photos.
Thanks again for your time.

**Comment by markummitchell** [comment]
I was worried that the file had a virus so I removed it. It turns out that the file extension actually should be 'webp' instead of 'jpg'. Webp is a new format that can be read by at least some browsers. More information is at https://developers.google.com/speed/webp.

**Comment by KRai2007** [comment]
Thank you so much!
I use screenshot to catch the curve and create a new file.
Now it works well in ENGAUGE.
