### ISSUE TITLE
Mistake in export curve to .csv file in Czech location

### ISSUE THREAD

**Issue by petr-opava** [markummitchell/engauge-digitizer#364]
Hello, I like to using this software. There is mistake in export to .csv file in Czech location . If I set export option to Delimiters - Semicolons , the .csf file looks different (see below) then I expected.

The format displayed in Export format settings window (it is OK)
# x;Curve1
1,73922;1,1804
1,76078;1,6232
1,80819;3,4817

but the format saved in .csv file is wrong 
# x, Curve1
"1,73922", "1,1804"
"1,76078", "1,6232"
"1,80819", "3,4817" 

Could you fix it it?

Thanks!

Petr Bjalek

**Comment by markummitchell** [comment]
Thank you for the request. I am looking into it now

**Comment by markummitchell** [comment]
The behavior is still the same, with CSV and TSV files using commas and tabs respectively as the default behavior. However, the export preview dialog now lets the user select the filename extension so he/she can see how the manual delimiter settings (commas, tabs, spaces, semicolons), CSV and TSV filename extension, and checkbox to override the normal CSV and TSV formats all work together. You can test a 64 bit Windows version at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/lhpt3937f7d8jhg6/artifacts
