### ISSUE TITLE
Curve fitting methods

### ISSUE THREAD

**Issue by ellboy** [markummitchell/engauge-digitizer#365]
It would be nice to have different curve fitting methods in the tool. As example many electronics parts have exponential parameter dependencies defined in the datasheets. There would be also very useful to have an export function to store the result.

**Comment by markummitchell** [comment]
That may be useful in some cases. To accomplish that, the different curve fitting methods would have to be identified, and implemented with new user controls. The testing would have to be extensive, with complete testing in cases over all combinations of cartesian and polar coordinates, linear and log scaling, and low or high dynamic range (1.2345 to 1.2346 versus 0.00001 to 1000000). Unfortunately, I am thinking the extra complexity could confuse users. Can just putting points closer together work for your datasheets?

**Comment by ellboy** [comment]
> Can just putting points closer together work for your datasheets?

That’s the way I do it right now. It works but requires the use of high order polynomials.

What do you think about an export function?

**Comment by markummitchell** [comment]
I would like to understand better. Any chance you could send a drawing or
image?

**Comment by ellboy** [comment]
I mean the possibility to save the polynomial coefficients after fitting.
![fit](https://user-images.githubusercontent.com/939641/72804808-a5ce4e00-3c51-11ea-9886-d4320a5fb6f1.PNG)

**Comment by markummitchell** [comment]
Oh, I thought you meant the curve fitting during drawing. This is much easier for me and definitely a good enhancement for everyone. I will aim for a flexible solution able to handle a range of functions.

**Comment by markummitchell** [comment]
And export features will be included (a button and also click and drag)

**Comment by markummitchell** [comment]
The curve fitting uses polynomials, with the x and/or y coordinates converted from linear to log scale according to the current curve settings. I also added easy export using dragging or the clipboard.
