### ISSUE TITLE
[Export Format] Interpolate Ys at evenly spaced Xs using Graph units as Interval

### ISSUE THREAD

**Issue by adamsmietanka** [markummitchell/engauge-digitizer#366]
1. The input window expects integers. The only way to interpolate at smaller interval is to use scientific notation. 
2. After exporting using the method in No. 1 Ok button becomes unresponsive. The only way to go back to ex. Raw Xs and Ys is to put a 'valid' int number back to the Interval input window.
3. When using the method described in No. 1 there is an approximation error with x = 0
![image](https://user-images.githubusercontent.com/42046760/72533684-db4ff180-3875-11ea-82f4-026f6f970550.png)

**Comment by markummitchell** [comment]
This can be tested on Windows by downloading from https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/186ymtnf4hmtnkwv/artifacts. Thanks for the input!
