### ISSUE TITLE
Can a command line be added to import file on Mac version of Engauge Digitizer?

### ISSUE THREAD

**Issue by Bridgettobehere** [markummitchell/engauge-digitizer#367]
Hi Mark (and all),
Thank you for the answers on Stackoverflow. Could you help with adding a command line to import .png/.jpg file (some line chart) on Mac version of Engauge Digitizer? The current command lines available do not work for Mac.
Thanks!

**Comment by markummitchell** [comment]
Have you tried specifying the absolute path name? Some of the related information at https://www.josharcher.uk/code/find-path-to-folder-on-mac/ may be helpful. If that does not work, I will probably need more specific information.

**Comment by Bridgettobehere** [comment]
Thanks Mark.
I got some temporary solution regarding the file path issue [here](https://apple.stackexchange.com/questions/379877/in-bash-how-to-open-png-file-in-a-mac-app-which-only-has-import-in-the-app-m/379897?noredirect=1#comment514428_379897).
Of course, it has not solved the root problem. But I hope it can give you some external reference.

**Comment by markummitchell** [comment]
Thanks for the input. Imports at startup required additional permission to load from the Downloads and Pictures directories. An error message still appears for startup imports in other directories (which fail) but now the error message explains what is happening so users can work around the issue.
