### ISSUE TITLE
Point Match Tool / select points without curve fitting

### ISSUE THREAD

**Issue by chen112p** [markummitchell/engauge-digitizer#368]
Hello, I would like to probe points on a picture using engauge digitizer. I want to output coordinates to be in the order of me clicking on the picture (not interrupted by the curve fitting). I believe the Point Match Tool (yello button) can do this job. Having blue (Curve point tool) or yellow selected, the output is always disrupted by the curve fitting result. GUI always shows blue crosshair after clicking. Please show me how to activate the Point Match Tool. Thanks!

Junting

**Comment by markummitchell** [comment]
I think what you want is Settings / Curve Properties / Connect As. Change from Function-Smooth to Relation-Smooth.
