### ISSUE TITLE
Reset or Fix Coordinate System

### ISSUE THREAD

**Issue by wsburbank** [markummitchell/engauge-digitizer#369]
I made a mistake when setting my coordinate system.  i.e. entered a wrong value.  I cannot seem to find a reset to remedy my mistake after I have digitized all my data.

Is this feature available?

**Comment by markummitchell** [comment]
Sometime you can just switch modes, fix the problem, and then switch back to the original mode. For example, if you have a negative axis coordinate then Log coordinates will not work - just switch to Linear coordinates (in Coordinates settings) and fix the negative number, and then switch back.

If this does not help, maybe you can post your file and I can try? Sometimes people do screenshots but that may be more work.
