### ISSUE TITLE
Engauge 12.0 crashes when defining y axis on right side of plot

### ISSUE THREAD

**Issue by computersrhard** [markummitchell/engauge-digitizer#370]
When I am defining the y-coordinates on the right side of the plot, engauge crashes every time. See photo, where y coordinates are on right side.
![image](https://user-images.githubusercontent.com/61297781/74988694-b6faae00-53fb-11ea-92c5-67a75d75d528.png)

**Comment by markummitchell** [comment]
Ok, I will look at this

**Comment by markummitchell** [comment]
It seems to be working for me, when I used Import(Advanced) and set the number of coordinate systems to 10, and the number of axis points to 4. It looks like you are trying to use only 3 axis points, but the graphs have 'floating axes', which means the x values for points on the y axis are unknown, and the y values for points on the x axis are unknown. To digitize floating axes in Engauge, specify 4 axis points. Each of the 4 axis points is specified with just a single coordinate (2 for x and 2 for y). 

The bottom right graph may or may not have floating axes, but all of the other graphs definitely have floating axes.

I was unable to get the crash you mentioned. If you could share your steps, I would like to fix that.

**Comment by markummitchell** [comment]
![Screenshot_20200223_121020](https://user-images.githubusercontent.com/1624606/75119212-99188d80-5635-11ea-8482-071580290749.png)
