### ISSUE TITLE
Czech language mistakes

### ISSUE THREAD

**Issue by TomPlasekMex67** [markummitchell/engauge-digitizer#371]
I found a mistake in the czech language version. Export under File should be "Exportovat" instead of "Vývozní". If I find more mistakes I'll write theme here :)

**Comment by markummitchell** [comment]
Many people, including myself, would be very happy if you could help improve some of the translations. You can suguest changes here or get a free account at Transfer (for https://www.transifex.com/engauge-digitizer/engauge-digitizer)
