### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by n2779510** [markummitchell/engauge-digitizer#373]
Interface crashes with Cancel on "Edit Axis Point".  `2017-05-23 7.17.32 Win 64Bit.`

Trying to use Date DD/MM/YYYY or YYYY/MM/DD.  
Date doesn't seem to let me enter in either of those formats when selected in Settings-Coordinates.

**Comment by markummitchell** [comment]
I found the problems which should be fixed. You can test a pre-release Windows 64 bit version at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/cmkfsss5tapfjd5n/artifacts.
