### ISSUE TITLE
Datetime coordinates: support for dates outside range 1970-01-01 00:00:00 to 2038-01-19 03:14:08

### ISSUE THREAD

**Issue by TorbjornT** [markummitchell/engauge-digitizer#374]
I've been testing Engauge a bit for time series data, but it seems it doesn't work for dates earlier than the UNIX epoch, and it seems to run into the "2038 problem" as well, even though I downloaded the 64-bit version.

In short: when defining axis points, any datetime outside the range specified in the title gets changed to 2038-01-19 03:14:08.

I used version 12.1 for 64bit Windows 10, the one without installer file.

**Comment by markummitchell** [comment]
A Windows 64 pre-release is available at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/51hbfdk1tvb4u43i/artifacts if you are interested. Thanks for the input!

**Comment by TorbjornT** [comment]
Hm, your commit message says "at least thousands of years", but the only difference seems to be that the start point of the valid range has changed from 1970/1/1 to (1970/1/1 minus 2^31 seconds).  Now any time outside the range 1901/12/13 21:45:52 to 2038/01/19 04:14:08  (all UTC+1) gets changed to 1901/12/13 21:45:52.

So seems like the number of seconds are still not using 64 bits. (The computer I'm running this on definitely is a 64 bit system, by the way.)

**Comment by markummitchell** [comment]
Must be working differently in Windows rather than Linux, which is rare. I will investigate.

**Comment by markummitchell** [comment]
Fix made for Windows. Test case added.
