### ISSUE TITLE
Are datetime coordinates automatically adjusted to UTC, based on the computer's timezone?

### ISSUE THREAD

**Issue by TorbjornT** [markummitchell/engauge-digitizer#375]
When specifying an axis point in datetime I note that the time is always changed by one hour. That is, if I specify 2000/01/01 12:00:00, the point gets saved with the time 2000/01/01 11:00:00.

The timezone of my computer is UTC+1, so are the timestamps changed to UTC automatically based on the computer's timezone? 

Is it possible to disable this behaviour?

**Comment by markummitchell** [comment]
I think the problem is fixed. You can test a pre-release for Windows at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/oc38nasiqxar3oc4/artifacts. I hope this takes care of your issue.

**Comment by markummitchell** [comment]
Now the pre-release for Windows 64 is at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/51hbfdk1tvb4u43i/artifacts

**Comment by TorbjornT** [comment]
Wow, that was quick! I'll do some testing sometime during the day, for this and the other issue I posted.

**Comment by markummitchell** [comment]
There is still an issue I need to think about. As seen in the regression testing, old files will have their times off by the local offset from GMT. I am thinking about bringing up a special dialog offering to fix this issue when an old file is loaded. There would also be an option to always automatically take care of the offset in the future, with the user able to adjust the offset.
