### ISSUE TITLE
Segment Fill Tool Usage

### ISSUE THREAD

**Issue by krzyklo** [markummitchell/engauge-digitizer#377]
Dear Mark, 
I have a lot of problems with using Engauge to digitize published drawings, which has frame around the figure. 
This frames act as axes, and has ticks, that are needed to give axes reference points, but Engauge detect just those horizontal lines, and not the real curve, that I would like to digitize. 

Would you be able to suggest, how to limit/restrict the Segment Fill Tool, to area, where there is curve? 
I would welcome any suggestion, how to approach this kind of pictures - do I need to edit them in external software, and "clean up" the frames?

![image](https://user-images.githubusercontent.com/1746970/77826209-fc23a580-7148-11ea-8582-2db57b602a5e.png)

![image](https://user-images.githubusercontent.com/1746970/77826367-d6e36700-7149-11ea-9204-1e58c6d108ab.png)

BTW. Thank you for excellent software, that I am using for many years, and share info about it with other users.
KrzyKlo

**Comment by markummitchell** [comment]
Sorry for the slow reply. I just saw your post.

As you probably have guessed, your curve is changing rapidly. With a thin line that can make the Segment Fill algorithm get stuck at gaps. You can vary the Setttings / Segment Fill settings. 

Another possibility is with Settings / Color Settings. Changing those values may help make the gaps disappear.

If nothing else works, you might also consider widening the image using a scaling tool in Gimp. I scaled the horizontal direction by four times and the curve looked pretty smooth.

The fact that the algorithm can successfully pick up the axis lines is maybe frustrating, but does not interfere with analysis of the curves (the algorithm does not quit when it finds the axis lines).

**Comment by markummitchell** [comment]
There seems to be a problem with the ordering of the points in your image, which makes the smoothed curve go through points in the wrong order. 

If you can send the original image then I can look at the gap problem. If you also send the dig file with bad point ordering then I can look at that too.

**Comment by krzyklo** [comment]
Dear Mark, 
Thank you for looking into this issue. 
Below are attached PNG files I would like to fit. 
![Breiland_JEM1994_fitting_axes_633nm](https://user-images.githubusercontent.com/1746970/78215559-570f2100-74ea-11ea-80cf-b1f154cbe58e.png)
![Breiland_JEM1994_fitting_axes](https://user-images.githubusercontent.com/1746970/78215610-727a2c00-74ea-11ea-80b1-050d41207248.png)

DIG files are not supported to past here, therefore I will provide them as links later.

**Comment by krzyklo** [comment]
Whether it is possible, to give user, and control on how this Segment Fill algorithm works? 
1. Algorithm take into account X-Y range given by user, after defining axes.
2. Input/Modify/Restrict area for searching for a curve, as Rectangular area: Mouse selected as  - two X1Y1, X2Y2 points, which would draw a Rectangle, and take 2 clicks that would define area for fitting
3. Add those Rectangles fitting results into Export. 

Just some thoughts..
 in reality, the analytic formulas for this curves is "damped cosine"... 

as I am writing algorithm to fit this kind of curves, maybe instead of going through Engauge, I need to just upload picture into R studio, get the axis scale points, and then "overlay" my simulation curves directly on the picture...

**Comment by markummitchell** [comment]
Just ignore the unwanted segment fill pieces (along axes ...) and use the good ones.
