### ISSUE TITLE
warping image scaned from book

### ISSUE THREAD

**Issue by hustlei** [markummitchell/engauge-digitizer#378]
I wanna digitalize image scanned from old book，like this：

![01](https://user-images.githubusercontent.com/7204734/79123723-5e2d0d80-7dcd-11ea-97f2-089f2fe946a8.jpg)

is there some method for this?
 or methods such as editable grid instead of axes should be added?

**Comment by markummitchell** [comment]
Hello, Engauge does not support this, but you may be able to use some other tool like https://snorpey.github.io/distort-grid/ I have not tried that tool. While looking for other free online tools I came across at least one website with malware so be careful.
