### ISSUE TITLE
PDF import with auto scan for multiple graphs

### ISSUE THREAD

**Issue by Kbeist** [markummitchell/engauge-digitizer#380]
Is it possible to add the following:
Import multi-page PDF?
Auto scan document for multiple graphs?

**Comment by markummitchell** [comment]
Sorry, but the changes required to implement those features would be too extensive.

If you have multiple graphs that are very similar, you may consider setting up the first one and then using the first as a template for the others. Use Import(Image Replace) to replace the image.
