### ISSUE TITLE
ParseDig.py "upgrade" method fails

### ISSUE THREAD

**Issue by jddmartin** [markummitchell/engauge-digitizer#381]
https://github.com/markummitchell/engauge-digitizer/blob/57a312418c71ffdabdfb93691fb423bb0453ec44/contrib/python/ParseDig.py#L320

When line (above) is reached (by running ExampleParseDig.py for example), python3 (3.6.9 on Ubuntu 18.04) fails with message: 
NameError: name 'callEngauge' is not defined

Changing to 
        self.callEngauge (["-upgrade",
                        digFile])

(i.e. adding "self." fixes problem).
Thanks! --- Jim.

**Comment by markummitchell** [comment]
Thanks. I have added and tested the fix.
