### ISSUE TITLE
Selected points from different series are overlapped by each other

### ISSUE THREAD

**Issue by zhongjingjogy** [markummitchell/engauge-digitizer#382]
![image](https://user-images.githubusercontent.com/9261231/83120122-31c21c00-a103-11ea-8a61-236c59b7d0d3.png)

I am using version engauge-digitizer 12.0. When selecting points for different series, the selected ones are overlapped on each other. It is hard to locate the new ones from a mess. 

There is certainly a solution to handle this, but I find it nowhere. Clear hints and instruction might be helpful for this issue.

Best regards

**Comment by markummitchell** [comment]
Sorry for the slow response.

View / Curves / Show Selected Curve
