### ISSUE TITLE
If several points have the same x-value, only one will be exported

### ISSUE THREAD

**Issue by FB1979a** [markummitchell/engauge-digitizer#383]
Hi Mark,
first a big 'Thank you!' for this great piece of software, that really helps me a lot!
I would like to report the following bug:
If you select several data points which have the same X-value, only one of the data points will be exported. The others don't appear in the exported file. I assume - based on some short tests - that only the point with the highest index value will be exported.
I am using version 12.1 on Windows 10 (64bit), a demo file is attached.
Many thanks!
Frank

[Export.txt](https://github.com/markummitchell/engauge-digitizer/files/4722250/Export.txt)
![Engauge](https://user-images.githubusercontent.com/66359362/83619404-1f753180-a58c-11ea-99fd-3fdf9d230674.png)

**Comment by markummitchell** [comment]
Hi Frank, you probably are still using the default curve setting, which is Function. Under Settings / Curve Properties you can change the curve type to Relation to get every point. As you probably know, a Function can have only one Y values for a specific X value. If you spread out your overlapping points, you should see red segments that indicate the points overlap too much. 

Even if you select Raw Points in Settings / Export Settings, I think the overlap will still cause problems until you switch to Relation.

Good luck
Mark

**Comment by FB1979a** [comment]
Hi Mark,
many thanks for your answer. This solves my problem and And I want to apologize for creating a false bug report out of lack of knowledge.
Maybe I can still use this opportunity for a short feature request: It would be very helpful, if the curser could be shaped like one chosses for the selected cuve in the Settings / Curve Properties. Matching e.g. a triangle shaped cursor correctly on a triangle shaped data point would be much much easier.

Thank you and best regards,
Frank
