### ISSUE TITLE
Highlighting for Segment Fill Tool

### ISSUE THREAD

**Issue by saaskins** [markummitchell/engauge-digitizer#384]
Been faithful user of Engauge Digitizer for many years. Thank you so much for the useful software.

I recently upgraded from v4.1 to v12.1. I like the new features but when I use the "Segment Fill" tool I am not getting the green highlighting to show which segments have been detected until I hover the mouse over the segment, in the old version all segments were displayed as soon as you activated the tool.

OS: Windows 10

**Comment by markummitchell** [comment]
That capability was lost during the rewrite a while back, but it will be restored since it probably is more user friendly.  Thanks for the suggestion.

**Comment by saaskins** [comment]
OK, thanks for your response. I definitely think it would be great to have the feature back, much faster when you are trying to figure out what discretization settings work, and also when you are using the tool. 

I've also noticed that modifying the coords of axis points is a bit more difficult now. In the old version it was a simple fast right click, in this version it seems like I have to select first and then right click and it seems really hard to make it work (need to click a bunch of time, end up accidentally moving the point, etc.

Thanks!

**Comment by markummitchell** [comment]
This will appear in the next release.
