### ISSUE TITLE
Locale setting using Flatpak

### ISSUE THREAD

**Issue by chazelas** [markummitchell/engauge-digitizer#385]
Hello,

Using Ubuntu 20.04, I have tried to install the flatpak version of engauge, and contrarily to the deb version I have no access to change the locale (I have no list available).
The phenomenon is the same with the snap version.

I suppose it has to do with the isolation of flatpak but I have no clue on how to fix this. (I am ready to make experiments under guidance)

Thanks for this wonderful package that helps me a lot in my work

Bruno

**Comment by markummitchell** [comment]
This has been fixed for both flatpak and snap. Thanks for the input.

I will try to release soon. Issue #386 must be finished first.
