### ISSUE TITLE
Verify and Edit Coordinate Settings

### ISSUE THREAD

**Issue by asf6** [markummitchell/engauge-digitizer#388]
I recently created a large project using EnDi.  The exported values did not make sense.  It would be very helpful is one could verify, and perhaps edit, the values entered for the coordinates.  The coordinate checker box works well to show what was selected on the graph, but I cannot find anyway to view or edit the values assigned to the coordinate box.

Thanks in advance,

adam

**Comment by markummitchell** [comment]
There are two options available to see how your coordinate transformation is working, so hopefully one works for you:
* In the status bar at the bottom right you can see the graph coordinates of the current cursor position
* You can select View / Grid Lines to get an idea of how the coordinates map to the picture image

The coordinate checker box is just for display. To change the transformation, move one or more grid points and/or edit the coordinates of one or more grid points using right-click on each point.

A new feature is currently being added for Guidelines to be displayed, but that is not available yet. You will be able to place a Guideline along a certain X or Y value.

**Comment by markummitchell** [comment]
Guidelines have been added for this and #386
