### ISSUE TITLE
Older Version 5.1

### ISSUE THREAD

**Issue by KlausDob** [markummitchell/engauge-digitizer#390]
I keep having problems with the new versions. With Segemnt Fill they no longer show me the lines. This was the case with version 5.1 and older. I would like to upgrade to a new version, unfortunately it can't. I upload a picture in the link of what the Fill segment looks like for me. I just thought it was better back then. Can you help me or is there an attitude?
https://ibb.co/7C2rtCS

**Comment by markummitchell** [comment]
I am looking at this now and will let you know.

**Comment by markummitchell** [comment]
There is a 64 bit Windows pre-release at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/rdaakih6k2601j64/artifacts if you want to test some fixes for this. Any feedback would be welcome.

**Comment by markummitchell** [comment]
I will close this. If there is feedback then it can be reopened.

This can be tested using https://github.com/markummitchell/engauge-digitizer/blob/master/README_windows_preview.md
