### ISSUE TITLE
feature request: repositioning of marker after placing it

### ISSUE THREAD

**Issue by wilthan** [markummitchell/engauge-digitizer#391]
When I identify a data point in a plot with a marker I often want/need to reposition it to position it exactly.
Right now, the only way I know to do that, is to switch to the select tool and move it with my mouse or the cursor arrow keys.
It would save a lot of time and clicks if we could improve that.
My suggestion: while on then curve point tool you can use a ctrl/shift/alt (on of them) key to change into the select tool temporarily to immediately fine tune the position of the just placed marker.

**Comment by markummitchell** [comment]
Some experimentation shows that after one or more points is added, the added points can be left in selected mode while Engauge state remains in 'Add Axis' or 'Add Graph' state. Then the arrow keys can be used to move the points around, without having to go back and forth between Engauge states.

Behavior with any other inputs (like the Delete key) may or may not good to also add - the user interface must be a balance between user friendliness and power. I will continue working on this. Your inputs are welcome.

**Comment by markummitchell** [comment]
This seems to be an EXCELLENT enhancement. Thanks!

You can test this using https://github.com/markummitchell/engauge-digitizer/blob/master/README_windows_preview.md.
