### ISSUE TITLE
Image is corrupted when loaded or pasted into the digitizer

### ISSUE THREAD

**Issue by RogueAgent991** [markummitchell/engauge-digitizer#394]
The attached images are representative of many that do not load properly into Engage Digitizer. I have confirmed this with ED versions 4.1 and 12.1

![040](https://user-images.githubusercontent.com/71994397/100315771-07480300-2f6e-11eb-9ed1-de5c9bc8ff79.jpg)
![080](https://user-images.githubusercontent.com/71994397/100315950-660d7c80-2f6e-11eb-8ef1-2cecab847d29.jpg)
![120](https://user-images.githubusercontent.com/71994397/100315955-67d74000-2f6e-11eb-8a8c-2da54b6dbe0b.jpg)

**Comment by markummitchell** [comment]
Have you tried View / Background / Show Original Image? 

If the background image setting is the problem, I will see what I can do to make this more clear in the future
