### ISSUE TITLE
Unable to interact with folder before finishing the checklist guide.

### ISSUE THREAD

**Issue by Pekton** [markummitchell/engauge-digitizer#398]
Engauge version: digit-exe-windows10-64-bit-without-installer-file-12.1

When I drag a file from a folder into the digitizer, the folder window will freeze until the checklist guide finished(close folder from desktop toolbar is possible). The checklist guide window will hide behind the folder, in case the folder obscures the guide window, I have to open the guide window from desktop toolbar. I think the guide window should pop up at top level.

**Comment by Pekton** [comment]
and in case the guide window obscures the image and the folder window also obscures the image in engauge main window, then I have to finish the checklist guide according to remember of the image.

**Comment by markummitchell** [comment]
I will try to improve this behavior.

**Comment by markummitchell** [comment]
Checkist Guide Wizard is no longer started from within the import handler which now exits quickly and releases the locked window. Also, the wizard is centered in the Engauge window so it does not show up underneath some other application's window where it can be easily overlooked.
