### ISSUE TITLE
Unable to change locale

### ISSUE THREAD

**Issue by joeheaven** [markummitchell/engauge-digitizer#400]
I'm using this fantastic software since version 4.1.

I'm happy that there is a constant evolution to make this even more useful.

However, there is one issue that drives me crazy and I'm not able to solve this:

I'm using the version 12.1 on Win10_64 without installer package (cannot install stuff on this machine here). Whatever I tried, I'm not able to change anything with respect to locale. Since I'm in Germany, Engauge does everythin in the German way, especially using a comma as decimal seperator. 

In Settings --> Main window --> Locale I only have an empty drop down, I cannot choose anything. In the axis definiton dialog I can only enter "German" numbers, the locale there is fixed to German.

I may have to mention that the Windows setting is changed to using the dot as decimal seperator system wide. Maybe this is in conflict? I even tried to delete all locale definition files except the English one without luck.

Can I force the use of the English locale?

**Comment by markummitchell** [comment]
Sorry for the delay. This has been fixed for the next release but if you want the patch for your current release then unzip the attached file into the Engauge directory.
[translations.zip](https://github.com/markummitchell/engauge-digitizer/files/6759150/translations.zip)

**Comment by joeheaven** [comment]
Maybe I didn't manage to do it right, still does not work, but I will wait for the release and check again. Thanks in any case so much for your efforts!
