### ISSUE TITLE
Warning when exporting a CSV file with more than 10,000 points

### ISSUE THREAD

**Issue by onealj** [markummitchell/engauge-digitizer#401]
I changed the x-axis until from the interval [60, 90] to [60e9, 90e9], but forgot to change the X-axis interpolation from 1 graph units to 1e9 graph units. Instead of having a file with 31 points, Engauge is trying to create a file with 31e9 points. This causes Engauge to become unresponsive while it's creating a very large file.

Obviously this is user error, but perhaps it would be a good idea to have a warning if the file exceeds some number of points (perhaps make this warning limit user-settable, but default to large number like 10,000, that takes less than a few seconds to generate the file).

I also forgot to save the project before exporting, so I can't abort the application without re-digitizing the graphs. Prompting to save the file before this large export would have saved me.

Engauge eventually crashed Windows by either exhausting available memory.

**Comment by markummitchell** [comment]
Fix was needed and applied. Tested with scale magnitude of 10 graph units, then axis magnitude was rescaled to 10^9 graph units and various (acceptable and unacceptable) delta values were specified in Export Settings dialog.
