### ISSUE TITLE
Encoding of Images in .dig files

### ISSUE THREAD

**Issue by yungHurz** [markummitchell/engauge-digitizer#404]
Hello, I am trying to read the image data from the .dig files CDATA section and decode it back to the original image. To my understanding the images are encoded in a base64 string, but when i try to decode them back it results in a broken file.

Also, when i manually encode an input image to base64 the resulting string is different from the one that gets stored in the .dig file.

Any help on how i can decode this data back to the original image would be greatly appreciated.
Thanks a lot.

**Comment by markummitchell** [comment]
The code in src/Document/Document.cpp may be helpful:

void Doocument::loadImage (QXmlStreamReader &reader)
{
   loadNextFromReader (reader);
   if (reader.isCDATA ()) {
     // Get base64 array
     QByteArray array64 = reader.text().toString().toUtf8();
      //Decoded array
      QByteArray array;
      array = QByteArray::fromBase64 (array64);
      // Read decoded array into image
      QDataStream str (&array, QIODevice::ReadOnly);
      QImage img = m_pixmap.toImage(); // Load old pixmap in case read fails
     str >> img; // Try to read new pixmap
     m_pixmap = QPixmap::fromImage (img);
