### ISSUE TITLE
Freeze on Settings -> Export Format

### ISSUE THREAD

**Issue by delcampo95** [markummitchell/engauge-digitizer#405]
When I go to Settings -> Export Format, the Export Format dialog does not appear.  However, the main Engauge window turns inactive (almost like there is a hidden dialog window somewhere), "dings" when I try to interact with it, also as if there is a hidden dialog window somewhere.

I didn't have this problem last week when I was first trying the software, but this week I noticed that when I launched Engauge, the main application was hidden, almost like it was on another monitor.  I had to use Windows trickery to make it appear again.  Is it possible that other dialog windows like Export Format are now appearing on a "ghost" monitor?

Worth noting that I have 4 monitors in my home office, and 3 in my work office, and I first launched Engauge on the work rig, and now I am trying it on the home rig.  Is it possible that the dialog is looking for a "lost" monitor, with no error handling to make it show up on an existing monitor?

**Comment by delcampo95** [comment]
Never mind:  I found the dialog box in multi-monitor purgatory.  I'm not sure if there's a way to detect when a dialog box is lost like this in code, but I certainly have my short-term solution:

https://www.ideateinc.com/blog/2017/06/missing-dialog-boxes

**Comment by markummitchell** [comment]
There is a '-reset' option when starting up  to handle situations where a monitor was removed but an Engauge window still comes up in the missing monitor. The reset option brings up the window in the primary monitor. Operating system methods for finding missing windows are a bit unfriendly but they can also be helpful.
