### ISSUE TITLE
Settings tab doesn't open

### ISSUE THREAD

**Issue by sernikbulando** [markummitchell/engauge-digitizer#412]
When wanting to change the coordinates from linear to logarithmic the settings tab doesn't open. The menu on top goes grey as if it is open. I'm on a windows

**Comment by sernikbulando** [comment]
-

**Comment by Jackk242** [comment]
@sernikbulando what is your engauge digitizer software version?

**Comment by sernikbulando** [comment]
The last one, 12.1

**Comment by Jackk242** [comment]
Tell me everything you do from the point of starting the program to wanting to go into the settings tab

**Comment by sernikbulando** [comment]
Hi,
I open the programm. Import the image I want to digitalize, with the pop-up
menu for the introduction I enter the names of the curves, set the 3 points
for the axis and start to pin the points of data. And now I click on the
settings tab on the top of the programm, it goes grey, but doesn't open the
menu to change from linear to logarithmic.

**Comment by Jackk242** [comment]
Can you send me your particular file? I will walk through your steps myself and compare it to sample graphs to see what differences come up. My email is listed below:

jackk242@gmail.com
