### ISSUE TITLE
Digitization of curved graphs

### ISSUE THREAD

**Issue by Miketheuniverse** [markummitchell/engauge-digitizer#425]
I am in the process of writing my dissertation comparing various graph digitization software and museum paper based data. 

Museum relative humidity and temperature data has been recorded on hygrothermograph charts, which is a paper placed on a rotating drum. 

Because the charts are placed on a rotating drum, the charts are curved. I have tried to digitize the charts but am getting incorrect data, which I assume is because the charts have a curved shape and are not square. 
![test image](https://user-images.githubusercontent.com/98713591/183073777-bd623d09-7259-451c-abb7-46416da0979a.jpg)

Is there anyway around this issue or is this due to user error? I have attached an image of an example chart I am trying to digitize for reference. Thank you for any help you can provide.

**Comment by darinddv** [comment]
(not a dev on this project) Hope I'm not too late for your dissertation, but have you tried any image scaling methods to remove the curvature? Something like an affine transform (preserves parallelism) should be able to squish it back into a square. 
I'd imagine you'll have more trouble with the grid but you may have already found a solution. Good luck!

**Comment by darinddv** [comment]
> (not a dev on this project) Hope I'm not too late for your dissertation, but have you tried any image scaling methods to remove the curvature? Something like an affine transform (preserves parallelism) should be able to squish it back into a square.
I'd imagine you'll have more trouble with the grid but you may have already found a solution. Good luck!

**Comment by darinddv** [comment]
@Miketheuniverse 
(not a dev on this project) Hope I'm not too late for your dissertation, but have you tried any image scaling methods to remove the curvature? Something like an affine transform (preserves parallelism) should be able to squish it back into a square.
I'd imagine you'll have more trouble with the grid but you may have already found a solution. Good luck!
