### ISSUE TITLE
Cannot read file [...] from directory [...] (import error)

### ISSUE THREAD

**Issue by J-Saeedi** [markummitchell/engauge-digitizer#426]
This is my first attempt to use `engauge-digitizer` on my windows 11 desktop.
engauge version is *12.1* and I tried both the MSI installer and zip file (without the installer). but the image cannot be imported into engauge-digitizer.
here is a screenshot of the error.
![2022-10-22_21-01](https://user-images.githubusercontent.com/103021017/197354218-1dd2bc77-1780-46c8-84d6-cff3c05a140f.png)

in #363 a solution was introduced that take screenshot from the image and then use the engauge-digitizer again.
I suggest a comprehensive examination of this issue because in some cases, taking screenshots may lead to reduced image quality and that should not be acceptable.

**Comment by J-Saeedi** [comment]
There is my file that I want to import in software:
https://user-images.githubusercontent.com/103021017/197355166-4f732b56-7b88-4a4c-9610-9338b0113a09.png

**Comment by Fleurn0** [comment]
Yes I was looking into the same thing, and noted the last release was 2019, so there is likely no Windows 11 installer.

I'm not sure @markummitchell can update for Windows 11 - if not you may want to try Automeris web digitizer, or the University of Tennessee online digitiser
