### ISSUE TITLE
zoom on mouse wheel event should only work when Ctrl is pressed

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#65]
Currently mouse wheel event produces both up/down and zoom in/out events on main window. Zoom in/out should only be executed when Ctrl is pressed when mouse wheel event happens (see https://stackoverflow.com/questions/17204142/capturing-modifier-keys-qt for reference)
I used the method  suggested in best answer there and it worked for window when no Ctrl was pressed. But when it is pressed, events from mouse wheel scroll still leaks to window up/down navigation from zoom in/out event. See https://doc.qt.io/qt-5/qkeyevent.html#modifiers maybe one must use function suggested there.

2) It seems to me that you have reversed the zoom and mouse wheel event direction, compare it, say, with any browser or text editor.

**Comment by markummitchell** [comment]
Much better now.

**Comment by crayxt** [comment]
Yes, but wheel events still leak, e.g. when you are zooming in, it does zoom in, but in the same time some image is going up/down - e.g. reacting as if mouse wheel is being scrolled without Ctrl being hold.

**Comment by markummitchell** [comment]
Ok, I think I understand. The event needs to be consumed. What platform are you testing on?

**Comment by crayxt** [comment]
I am testing on Windows 7, with builds provided by appveyor https://github.com/markummitchell/engauge6/pull/69

**Comment by markummitchell** [comment]
Control+wheel now should do zooming and wheel only should do scrolling

**Comment by markummitchell** [comment]
Tested in Windows and LInux

**Comment by crayxt** [comment]
Confirm for Windows version, thanks
