### ISSUE TITLE
MacOSX builds

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#67]
I would like to make builds for OSX. Does anybody know if there are any free resources for building OSX releases? I'd buy a machine but I am trying to save money right now.

**Comment by crayxt** [comment]
need to look into it. For now we can setup travis to run test builds on osx as well.

**Comment by jkulesza** [comment]
@markummitchell, as a point of user feedback: I appreciate any effort you put toward OSX builds.

**Comment by crayxt** [comment]
@markummitchell It seems like you can OSX in VMWare/Virtualbox

**Comment by markummitchell** [comment]
That is good news. I always thought I had to have a Mac computer to install the OS. I've ordered the Snow Leopard DVD. 
@jkulesza - coming soon!

**Comment by jkulesza** [comment]
> I've ordered the Snow Leopard DVD. 

This is one (of many) gripes I have with Apple: versions have been changing quickly (and carry multiple names).  I believe that Snow Leopard describes version 10.6.x of the OS.  When I bought a new machine in September 2014, it came with 10.9.x (Mavericks).  A new machine in December 2015 came with 10.11.x (El Capitan).  I skipped 10.10.x (Yosemite) along the way.

I would be careful building installers for an older version when I suspect (perhaps unfairly) that most users are on newer versions.  That said, I'm unsure how you can acquire newer versions to build for / test with.

Hopefully there are no issues with that; however, I wanted to call out the point of caution.

That said, when you get an installer built, I'll be happy to test it and provide feedback.

**Comment by markummitchell** [comment]
Thanks for the offer. My understanding of https://en.wikipedia.org/wiki/Mac_OS_X_Snow_Leopard is that 10.6 could be installed and then upgraded through the Mac Store. Hopefully a build on 10.11 will work on other recent versions.

**Comment by jkulesza** [comment]
> Hopefully a build on 10.11 will work on other recent versions.

I would guess it to be the case.  I recently took my 10.9 machine and upgraded it directly to 10.11.  Thus far, all installed applications have functioned without issue on 10.11.  Hopefully there is just as strong backward compatibility (especially since Engauge shouldn't be tapping into the advanced/recent features of Apple's API).

**Comment by crayxt** [comment]
depends on https://github.com/markummitchell/engauge6/issues/50

**Comment by crayxt** [comment]
Is this mandatory for release 7? Or you ok to ship it with later releases

**Comment by crayxt** [comment]
Any news on subject?

**Comment by markummitchell** [comment]
Slow progress. I will look at the AppVeyor builds for guidance.

**Comment by markummitchell** [comment]
Duplicates issue #50.

**Comment by markummitchell** [comment]
A dmg file is available in the 'osx' branch in dev/osx/engauge.dmg.

**Comment by jkulesza** [comment]
@markummitchell: the DMG you posted installs and appears to run appropriately on 10.11.3.  Let me know if there are any particular features/behaviors you'd like me to test.

**Comment by markummitchell** [comment]
Much appreciated. I think we're good for now.

**Comment by crayxt** [comment]
Yay!
