### ISSUE TITLE
Rename repository from engauge6 to engauge

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#70]
This is a heads up that the project name should probably be renamed from engauge6 to engauge, since there will be a version 7 release pretty soon (in a few days probably).

There is some new functionality that requires a new Version 7 DIG file format, since the new features do not work with Version 6 DIG files. The new features are (1) multiple coordinate systems and (2) 4 axis points. These are accessed using 'File / Import(Advanced)'.

According to github documentation, going to the old URLs will result in a redirect to the new repository. The biggest hassle may be updating links in cloned snapshots.

**Comment by crayxt** [comment]
I renamed my fork to test CI integration:
1) In Appveyor you need to attach your project again
2) Travis handles this automatically, just go to your settings and sync with github
3) Build status badges must be updated in README.

**Comment by markummitchell** [comment]
Did you get an email from AppVeyor? I tried to set up an admin account for you. I'm done for the evening.

**Comment by crayxt** [comment]
Yes I did. Thanks,

**Comment by markummitchell** [comment]
Renamed, and updated hyperlinks seem to work. Builds are successful.
