### ISSUE TITLE
Suggestion: Ability to fine tune points by arrow keys

### ISSUE THREAD

**Issue by np-8** [markummitchell/engauge-digitizer#81]
Now it is only possible to move the selected/last set point with mouse. It would be awesome to move the point with arrow keys for fine tuning. It would be best it arrow keys would move the point by smallest possible increment in the greatest zoom, and faster in smaller zoom levels. Also, Shift+Arrow keys could move the point 10x or 20x faster.

**Comment by markummitchell** [comment]
Are you running in Windows? The select points currently move with the arrow keys in Linux.

**Comment by markummitchell** [comment]
This seems to be working already in both Linux and Windows. The extra feature of having Shift+Arrow go faster is probably overkill since holding down an arrow key triggers autorepeat, which makes things happen quickly.

**Comment by markummitchell** [comment]
Test in version 7
