### ISSUE TITLE
Location of engauge.log file

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#84]
When I drag and drop an image file to Engauge, it creates engauge.log file in the same directory where image file is located. Same applies to images opened in command line. Was it done for convenience?
I think that log file placement logic should be like this:
1) Try to place it in same directory where engauge.exe is.
2) if above directory is not writeable, put it to $HOME.
3) if $HOME is not available, put it to TEMP.

**Comment by markummitchell** [comment]
Seems to be done

**Comment by crayxt** [comment]
Confirmed on Windows
