### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#85]
It would be good to provide users with translated UI. Usually you just provide source file for translation and show your willingness to accept such translations, and over the time people will contribute.
Just tried to generate source translation file
```
[user@linux engauge6]$ lupdate-qt5 engauge.pro -ts out.ts
WARNING: Project ERROR: Unknown module(s) in QT: help
/home/user/engauge6/src/Checklist/ChecklistGuideWizard.cpp:23: Class 'ChecklistGuideWizard' lacks Q_OBJECT macro
/home/user/engauge6/src/Dlg/DlgAbout.cpp:9: Class 'DlgAbout' lacks Q_OBJECT macro
Updating 'out.ts'...
    Found 380 source text(s) (380 new and 0 already existing)
```

**Comment by markummitchell** [comment]
Anything else?

**Comment by crayxt** [comment]
So far so good for release 7.
TODO:
1) Put to separate directory, like translations;
2) Compile translated TS files to final message catalog files (.qm I think) in release build scripts;
3) Link with some external translation service, like Transifex. Special care needed since it tends to pollute git history. Probably manual pull from such service is preferred.

**Comment by markummitchell** [comment]
Translations can be done at Transifex (https://www.transifex.com/self-31/engauge-digitizer-1/dashboard/), although I do not know if translators also need accounts there, and what happens after the 15 day free trial.

**Comment by crayxt** [comment]
@markummitchell I can release the engauge-digiziter project name.
Open-source projects must be served free on Transifex

**Comment by crayxt** [comment]
@markummitchell I have deleted the engauge-digitizer organization, so you can create your own with that name.

**Comment by markummitchell** [comment]
Very good. I set up 'Engauge Digitizer' in just a few minutes, and can
easily do the same again.

**Comment by markummitchell** [comment]
I will immediately.

**Comment by crayxt** [comment]
@markummitchell what happened with engauge-digitizer organization name on Transifex? Why didn't you use it

**Comment by markummitchell** [comment]
I replaced the old group. You should be getting an invitation.

**Comment by crayxt** [comment]
https://www.transifex.com/engauge-digitizer/ still gives 404
No invitation received ;)

**Comment by markummitchell** [comment]
I fixed the url so transifex.com/engauge-digitizer works. I must have put
in a bad email address so your invitation was lost, but the project is open
to any volunteers.

**Comment by crayxt** [comment]
Ok, I think this one could be closed. Thanks
