### ISSUE TITLE
6.2 on ubuntu runs but not functional

### ISSUE THREAD

**Issue by holla2040** [markummitchell/engauge-digitizer#88]
Mark,
u14.04's 32-bit distro engauge5.2 has buggy exports for graphs with multiple curves, see attached. So I tried 6.2 from digit-exe-debian-linux-32-bit-installer-6_2.run, installs fine, runs but no menus and all functionality disabled, see attached.  Is there something else I need to install? Thanks.
Craig

![ecc83 philips 1953](https://cloud.githubusercontent.com/assets/1024542/13384179/6e2f97f0-de50-11e5-918e-a2b1e1b85c15.png)

![screenshot from 2016-02-28 19 18 22](https://cloud.githubusercontent.com/assets/1024542/13384200/aaaef108-de50-11e5-99fb-625767237010.png)

**Comment by markummitchell** [comment]
Are  you running ubuntu 12.04 32 bit or 64 bit? I'd like to install the same operating system in a virtual machine to look into this. This issue seems like it might be related to similar issues seen in Mac OSX.

**Comment by holla2040** [comment]
Oh crap, I meant to say ubuntu 14.04 32-bit. I'll edit my original post.

**Comment by markummitchell** [comment]
I tried with ubuntu 14.04 32-bit, and saw the menu bar appearing at the very top of the screen, which is the same behavior that other applications have in ubuntu. Import and Open also worked.

**Comment by holla2040** [comment]
I'll try 6.2 on a different desktop in the morning and comment.

ETA on v7? A couple months?

**Comment by crayxt** [comment]
@holla2040 much closer

**Comment by holla2040** [comment]
OK, tried a different desktop also running u14.04 32-bit, same result, no menu. 

But then kicked myself because qt5 libs were missing ,duh. 

holla@frampton[501]: ldd /usr/local/engauge/engauge.exe
        linux-gate.so.1 (0xb7761000)
        liblog4cpp.so.5 => not found
        libfftw3.so.3 => /usr/lib/i386-linux-gnu/libfftw3.so.3 (0xb756a000)
        libQt5Help.so.5 => not found
        libQt5PrintSupport.so.5 => not found
        libQt5Widgets.so.5 => not found
        libQt5Xml.so.5 => not found
        libQt5Network.so.5 => not found
        libQt5Gui.so.5 => not found
        libQt5Core.so.5 => not found
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xb7476000)
        libm.so.6 => /lib/i386-linux-gnu/i686/cmov/libm.so.6 (0xb7430000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb7413000)
        libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xb7265000)
        /lib/ld-linux.so.2 (0xb7764000)

installed qt5-default qttools5-dev-tools and ldd now showed all libs installed. same result, no menu. 

Moved onto to a server running debian/jessie 32-bit, engauge here works fine, menus, multiple curves, export, etc. 

I suspect the menu is there but with 0 height. some legacy qt setting screwing up qt5. my home dir is quite old. looking into this now. 

Thanks for the help.

**Comment by holla2040** [comment]
Found this
https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

did this
sudo apt-get remove appmenu-qt5

/usr/local/engauge/engauge now works fine.
