### ISSUE TITLE
clang analyzer found 6 bugs

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#89]
Run in fedora rawhide.
Attached is zipped results file
In short
![capture](https://cloud.githubusercontent.com/assets/33132/13392960/14b3f15c-df00-11e5-84bd-bf4e9bf72e77.JPG)
[2016-02-29-070428-5970-1.zip](https://github.com/markummitchell/engauge-digitizer/files/150765/2016-02-29-070428-5970-1.zip)

**Comment by markummitchell** [comment]
I made changes for each of the 6 issues.

**Comment by crayxt** [comment]
New round, seems like not all of them were fixed
![capture](https://cloud.githubusercontent.com/assets/33132/13837648/36a6908a-ec2f-11e5-9082-456d19bd4ecd.JPG)

**Comment by markummitchell** [comment]
I've removed all but one error in Segment/SegmentFactory.cpp that seems to be a false positive.

**Comment by crayxt** [comment]
Perfect!
