### ISSUE TITLE
Toggle the full path of file in Engauge titlebar

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#95]
Sometimes I have files with same names in different directories. I would like to see a full path to files in Engauge titlebar in such cases.

Suggestion: Configurable way to display file name with full path in Engauge titlebar.

**Comment by crayxt** [comment]
Also when full path is shown it is better to have file extension not stripped

**Comment by markummitchell** [comment]
Should be working now.

**Comment by crayxt** [comment]
I confirm, but here is the thing:
Open up dig file, go to Settings - Main Window (btw resulting window named MainWindow without space)
Uncheck Include title bar path, press OK
Now Title bar has full path, but the state of document shows like it is changed (* added to title bar) even though there are no actual changes to dig document itself.

Same applies to Clear recent file list action. https://github.com/markummitchell/engauge-digitizer/issues/94

**Comment by crayxt** [comment]
Actually changing any setting causes Document to look like it is changed!

**Comment by crayxt** [comment]
Promoted to separate issue https://github.com/markummitchell/engauge-digitizer/issues/99
