### ISSUE TITLE
Changing any setting causes Document to act like it is changed

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#99]
Open up dig file, go to Settings - Main Window (btw resulting window named MainWindow without space)
Uncheck Include title bar path, press OK
Now Title bar has full path, but the state of document shows like it is changed (* added to title bar) even though there are no actual changes to dig document itself.

**Comment by crayxt** [comment]
Actually changing any setting causes Document to look like it is changed!

**Comment by markummitchell** [comment]
Should be fixed now.

**Comment by crayxt** [comment]
@markummitchell So it happened due to settings being remembered between sessions?

**Comment by markummitchell** [comment]
The main window settings were applied through the undo/redo stack, which
really should only be used to apply changes to the document. The "unsaved"
asterisk was appearing when a change was made to either the main window
settings (bad) or the document (good). Now those settings are applied
without involving the undo/redo stack. My mistake.

**Comment by crayxt** [comment]
@markummitchell I also see this behaviour when changing cursor size, for example. Is it applied to document itself?
Anyway, the overall shape is good for release.

**Comment by markummitchell** [comment]
The General settings affect the Document directly, and are actually stored in the Document files. So, changing cursor size is changing the Document.
